apiVersion: batch/v1
kind: CronJob
metadata:
  name: recyclarr
spec:
  schedule: "0 */6 * * *" # Every 6 hours
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: recyclarr
        spec:
          restartPolicy: OnFailure
          containers:
            - name: recyclarr
              image: artifactory.local.hejsan.xyz/docker/recyclarr/recyclarr:8
              args: ["sync"]
              envFrom:
                - secretRef:
                    name: recyclarr-secrets
              volumeMounts:
                - name: config
                  mountPath: /config/recyclarr.yml
                  subPath: recyclarr.yml
                  readOnly: true
              resources:
                limits:
                  memory: 256Mi
                  cpu: "0.5"
                requests:
                  memory: 128Mi
                  cpu: "0.1"
          volumes:
            - name: config
              configMap:
                name: recyclarr-config
