apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: alertmanager-data-to-canonical
  namespace: monitoring
spec:
  volumeSnapshotClassName: linstor-snapshot
  source:
    persistentVolumeClaimName: alertmanager-kube-prometheus-stack-alertmanager-db-triple-alertmanager-kube-prometheus-stack-alertmanager-0
