apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-shared-nfs-pvc
spec:
  storageClassName: "manual"
  volumeName: shared-nfs-csi-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 110Ti
