apiVersion: v1
kind: Secret
metadata:
    name: minecraft-secrets
    namespace: minecraft
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:2PoNzJZI5u9W3zib2kjffACBKDxvzPLvNngQ7YX5eSm2qe93mWityA==,iv:Pcd771UH2FGHAUudqxndcp8lS/OXLoTzwIItugjHQ14=,tag:Iq39lR7jHnhCbkLZQK9KMQ==,type:str]
sops:
    age:
        - recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RngxUjR6SWxJS2l2VnJN
            UFY0SCtDb0owQU43cUl2dUw3cjRHcHFYdjJVCm03amtPWVdTZGtqbFZVMThnengy
            SHpjcXRwMHJTTnM1b2g0VVpqc1VKdzQKLS0tIHNHSEt4ZWR3OE9wZXFDU2tGeVdV
            MFd6NjF0alFUYXVEVjdWa2lmL2h1OFUKs0ZpJfxtMQWGNlsD6rLf4qmZF4KYMKD0
            AJ5bUTqUDvsmrmSpL6WFnSKts/k0R0sHn5crCPqDTX/O8EaKrmb0Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T18:51:47Z"
    mac: ENC[AES256_GCM,data:Sq0YX/LNqNUH7Hic4ppSkev433aawKhh4Eo4Jyi0se6zmymcOh6f940M1zZSZVukS8NZZIPuJkgkeaTUrtpiWyd6qL0tIb5IUJkIzRDZ1SVkjtDsODFornQfkyr6xvngFMh+8fnKre/p2O8KrxFSwutUA6SAT3nr+cDf10099ek=,iv:zEzcrDzriw1XgjSv18eZraUJgYV6HlCFi5j2w2VpOto=,tag:0fkrnrgeiK8B2vwCHDg37w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
