apiVersion: v1
kind: Secret
metadata:
    name: minecraft-secrets
    namespace: minecraft
data:
    RCON_PASSWORD: ENC[AES256_GCM,data:b/kpAPoy8N52SlAlXO5BfcvOlV2/KnUO7lM/VyT1wnzOWX08LywIpg==,iv:4tbUBFZDV1hxggnnJYpHJ9HxthXdBiWWnQZZzl5lOCE=,tag:d2qkVL4CUvdPafxYoOGz3Q==,type:str]
sops:
    age:
        - recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZDIvV1ZNTUI3SHBvZjdE
            S3h3bzlpU04wc2hzR3hjZ0kycldyZWJNdEUwCktUL3lBRU5YUGJzdFVZcFhhSHpq
            TEFWMHI2ZDNpODU3TWVPcTFyMG1mVEEKLS0tIFNIaVJvS3hGb0Fod0tOMTZNa2du
            bndHdFM3aE8vMzZqZWhWZnFuZW0rWVEKyRUfbl33XMafZ7nIIvSqd+nH7arnybH1
            QDswl29hvcn+rnX+/+prJ8xnvhSny7dgOreY4/3nDBKVHG1ukK31Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T17:36:55Z"
    mac: ENC[AES256_GCM,data:2MMP9d3ob+lsXOGG/4qqYpOhSEBrDxRy7WrdgqeVn8FnzI/ako1MrHxb34IRXS6CPdCTpZNBDAmi0lzEd+9Tq3ihpERNJsq3n7NI5JL/uGb5cICPym49ueCbzip4izAcU7mDclOCSJk2XihD2YPaZmxLCqEqQ87VppmkHL2/+Lo=,iv:kp801YTLJdzbUqpArUGZ7xoeWk43Vlv/v25P5PUFTow=,tag:k8qq1fughJg1TTr/ZNcXpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
