apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-data-linstor
  namespace: monitoring
  annotations:
    storage-migration.source-pvc: alertmanager-kube-prometheus-stack-alertmanager-db-alertmanager-kube-prometheus-stack-alertmanager-0
    storage-migration.phase: copy-target
  labels:
    app.kubernetes.io/instance: kube-prometheus-stack-alertmanager
    app.kubernetes.io/part-of: monitoring
    storage-migration: alertmanager-longhorn-to-linstor-2026-09
    storage-migration-phase: copy-target
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor-final
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
