apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-kube-prometheus-stack-prometheus-db-linstor-copy
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    app.kubernetes.io/instance: kube-prometheus-stack-prometheus
    app.kubernetes.io/part-of: monitoring
    storage-migration: prometheus-longhorn-to-linstor-2026-09
    storage-migration-phase: copy-target
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor-final-bootstrap
  volumeMode: Filesystem
  resources:
    requests:
      storage: 153Gi
