apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-final
  labels:
    app: radarr-11
    storage-migration: radarr-11-linstor-final-2026-09
    storage-migration-phase: cutover-complete
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor-final
  resources:
    requests:
      storage: 3Gi
