apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-config-final
  annotations:
    storage-migration.source-pvc: seerr-config
    storage-migration.phase: cutover-complete
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor-final
  resources:
    requests:
      storage: 1Gi
