apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-config-linstor
  labels:
    app: seerr
    storage-migration: seerr-linstor-canonical-2026-09
    storage-migration-phase: cutover-complete
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor
  dataSource:
    name: seerr-data-to-canonical
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  resources:
    requests:
      storage: 1Gi
