apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: seerr-data-to-canonical
  labels:
    app: seerr
    storage-migration: seerr-linstor-canonical-2026-09
spec:
  volumeSnapshotClassName: linstor-snapshot
  source:
    persistentVolumeClaimName: seerr-config-triple
