apiVersion: apps/v1
kind: Deployment
metadata:
  name: pterodactyl-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pterodactyl-postgres
  template:
    metadata:
      labels:
        app: pterodactyl-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pterodactyl-secrets
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pterodactyl-secrets
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: pterodactyl-secrets
                  key: DB_DATABASE_NAME
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          ports:
            - containerPort: 5432
              name: postgres
          resources:
            requests:
              cpu: "0.2"
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: pterodactyl-db-pvc
