apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-init-image
  namespace: nfs-tools
data:
  # Updated by CI pipeline via k8s-deploy-image job
  image: artifactory.local.hejsan.xyz/gitlab-registry/josmase/infrastructure/nfs-stale-init-container:2026-06-27-8aee1270
