apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/gitlab
  - ../../../base/gitlab-runners
  - ../../gitlab
  - ../../gitlab-runners

components:
  - ../../components/prune-protection
