apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: gitlab-postgresql-to-canonical-v2
  namespace: gitlab
spec:
  volumeSnapshotClassName: linstor-snapshot
  source:
    persistentVolumeClaimName: gitlab-postgresql-triple
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-postgresql-linstor-v2
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: linstor
  dataSource:
    name: gitlab-postgresql-to-canonical-v2
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
