apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-pvc-bazarr-0-new
  namespace: media
  labels:
    media-app: bazarr
    app: bazarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  selector:
    matchLabels:
      bazarr-pvc: "true"
  resources:
    requests:
      storage: 2Gi
