apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-9084261f-0523-404f-b815-462ec3b3d364
  labels:
    media-app: bazarr
    app: bazarr
    kustomize.toolkit.fluxcd.io/name: apps
    kustomize.toolkit.fluxcd.io/namespace: flux-system
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: 9084261f-0523-404f-b815-462ec3b3d364
    volumeAttributes:
      numberOfReplicas: "3"
      staleReplicaTimeout: "20"
  volumeMode: Filesystem