apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-0a7d24e9-409a-4a0c-9f85-d133a4a437ef
  labels:
    media-app: bazarr
    app: bazarr
    bazarr-pvc: "true"
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: 0a7d24e9-409a-4a0c-9f85-d133a4a437ef
    volumeAttributes:
      numberOfReplicas: "3"
      staleReplicaTimeout: "20"
  volumeMode: Filesystem
