apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-pvc-bazarr-0
  namespace: media
  labels:
    media-app: bazarr
    app: bazarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
