apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/media/radarr-template
  - persistence.yaml

namePrefix: radarr-1-

labels:
  - includeSelectors: true
    pairs:
      app: radarr-1

patches:
  # Patch the IngressRoute hostname and service reference
  - target:
      kind: IngressRoute
      name: radarr
    patch: |
      - op: replace
        path: /spec/routes/0/match
        value: Host(`radarr-1.${DOMAIN_INTERNAL}`)
      - op: replace
        path: /spec/routes/0/services/0/name
        value: radarr-1-radarr
