apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-linstor
  labels:
    app: radarr-1
    storage-migration: clean-rebuild-2026-09-24
    storage-migration-phase: clean-target
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor
  resources:
    requests:
      storage: 2Gi
