apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-linstor
  labels:
    app: radarr-1
    storage-migration: radarr-1-linstor-final-2026-09
    storage-migration-phase: cutover-complete
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor
  resources:
    requests:
      storage: 22Gi
