apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-postgresql-triple
  namespace: gitlab
  labels:
    app.kubernetes.io/part-of: gitlab
    storage-migration: gitlab-linstor-2026-09
    storage-migration-phase: copy-target
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor-final-triple
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-redis-triple
  namespace: gitlab
  labels:
    app.kubernetes.io/part-of: gitlab
    storage-migration: gitlab-linstor-2026-09
    storage-migration-phase: copy-target
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor-final-triple
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-minio
  namespace: gitlab
  labels:
    app.kubernetes.io/part-of: gitlab
    storage-migration: gitlab-linstor-2026-09
    storage-migration-phase: copy-target
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor-final
  volumeName: pvc-51f1e398-d5a0-4132-8b41-7ea4dfd9e56a
  resources:
    requests:
      storage: 30Gi
