apiVersion: v1
kind: Secret
metadata:
    name: growlog-secrets
type: Opaque
stringData:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:Dve/X0abSd8Su/M9C954Q4qrqH2BCQh9Ma+4uGk7IS7xPPMCGj2ltadvPiU=,iv:YO1jW8pTDzE7GmpoeDJl5FuEGvYRkFR6CX5TWltBPCY=,tag:yiAByBE+FH4eNg/j8eY26Q==,type:str]
    ZERO_ADMIN_PASSWORD: ENC[AES256_GCM,data:Qz/B2Tpg/LoccjW2G3pQp/VWugS1FeTG6FfBAFuLzebAhewaj26Bo0kr9F0=,iv:oevEE9Kx248m25evxQrsRaub4AhUewnjGEqfjOavbWY=,tag:OLviOiRRusYzUjGcLCwu9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsS3F3SnRVeWRNS2gwZGpN
            dTFGYlYzQlVxQmdvTTc3em01aWYvY3ZmQzBJClVnZjZzTXVUS0JKV01DVk1kU2x5
            K0xCQkFTVG4zSEN3VTNrUmRMRWQ2RlkKLS0tIHhYMTJPOWsvQnZFdWVnT2FGa1ZX
            WFh2UlBNZ1hVcld5QVNIRnRqZUcwZDAKL8jUMIGnP1FMKtt1FiPfgHFy/B+jd5bN
            9uQihT2sWkAUI0eY6hy5IbDlR22qsAHNMxvWkuWlz5/tV4six2Mq3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T10:33:43Z"
    mac: ENC[AES256_GCM,data:tkOdC2XUJ+E/oUbCmS5kznO7jNQqzVnc3nHtR0c2dRsIiW+9OwqIE0V9OIsspIv7JPEJFZtbBHTFprHdQfpBDXv42Mpu4/oYHy4rWwMmZhJzjPD5VkffacmpCc3Sxd7SXuTZh7A+GKUGa2BXYItlxeq3e9b03lkhp33Y4EhaqAM=,iv:16CMQDkON0wXqHMbFZDu1qU9eLOovBcdBsPPlCKBnZ4=,tag:TIYjtReoTIrtONvbMeU3Iw==,type:str]
    version: 3.13.3
