apiVersion: v1
kind: Secret
metadata:
    name: growlog-secrets
type: Opaque
stringData:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:g3UzdUssqky1v0EQPfyWkMi9wSPcEHC/HMVZ+q2s/nVgS3S1NLve8QjqYEU=,iv:7HTJLWdA08K/4vQwYw75so9IZNOXzIP4cDNvW5yX6So=,tag:oJLtz3BG0WLc6sUOGSuWbQ==,type:str]
    ZERO_ADMIN_PASSWORD: ENC[AES256_GCM,data:Ji9OhhqhMDjVMSNqH0+SA7VrBUsMIzdOgrVFq3H5yRm0M0LN1KD3OmnkTnY=,iv:WSGmXbhoIz7hYkflDwbVt6jTXITq71P/MJKH5cZE35E=,tag:62oacVKS09h4Y5WWDzg2dg==,type:str]
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:xooURe/UkwgdJHkWYXclsLk7yYUNpDcepjZ01C9z64Nvu++8Cz43r1XUvDOJ/VxYmTXjfFWLGrHX6TXrFFePe69O7vAe6kazoKOa7SklhYKEeYYBueOr,iv:vEhtaIJ+3T0KaEe9iC4+NKCBPFkPSKz5gVrGFRuC/c0=,tag:aKOtyVx0Yl2rjEOOlZuVEA==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:XUPxc47MFwdXpgGUiaU09Yh+fouamc1t3Sflko1dqdF+8mvUH9breFyJ1g==,iv:oo1dEXHk0g8uTATdY0f9/tMumJ+D7tIyJ9YwHQxHgJc=,tag:ADl0CvvLFj5+7Grzsp2WMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZDVIZHllT25MU3JuZXZS
            dFFrUHpoV0hHWmtBSDlMYWJwaVZscS8rNGpRClJUR0FyRGFLNlR3TEQvUHlnQnRC
            YWI0dkVNS0QzdFJKRTJFZkNFdEEwWmsKLS0tIERod2xRekNEVmNyNVdudFAyWnlR
            cVNUeG1jUnNhRVMzRC9pNmh3T1ZuaGMK2LL+F4WNl20MYlXtiBoc2mYZGm+Im6aK
            r7Jp4wljFwfwTEBWnAaZs8hd3AFJ164cIcsLbeaPzc2WyPKBRUvxsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T19:30:03Z"
    mac: ENC[AES256_GCM,data:mby5bJZvddD5WW+3nww8unaMlAumie4aBmasN9/RbzhVvpY7AnszC0gT4qZNHIsfC1iTcV586EI0KEzHGQDVDin3dY3Ns6s/jl+/sKhJ5dloPphz5W/jYdby0oZ6eOSnGFbym0UwQg4jsG5XDgzCrv4BFNnZK+OW9ll2qdrztew=,iv:gHMKAolDjY+Agr2/AqJvBh7SHZBXKyjfnfWNNKht04s=,tag:n4FakUOnJT7HN4kemuRtlg==,type:str]
    version: 3.13.3
