apiVersion: v1
kind: Secret
metadata:
    name: llm-switchboard-secrets
    labels:
        app: llm-switchboard
type: Opaque
stringData:
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:tRs0q/01g5Aw9/oaPEqeobjHd7tF9yyNT0gymWKFvNGEAzj7j/JIAC9wARznjpfJHP75fkF5j4GbtC+7+D2O158fvskbgHmTxA==,iv:vmRA/thFw4yz7VDUhYxOe2vTH1rjV4lMVjjEd4fRy0c=,tag:7gGQILOnSgo3i806OLaYOg==,type:str]
    MODEL_ROUTER_API_KEY: ENC[AES256_GCM,data:VGvFcJhmCyfXDdcpXzbeBeglJhi69PZYpK2Ka+Wvx8crUd2o239KrAmA1hCN4UWsibcHDdsd8G2KzyW/DkcxQg==,iv:hAXoRJbstZX34Iqc+0VU4dQbhsqycfoPpDD6q0M19Gg=,tag:LG635lLaaa9nnhGaNEfCRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcnEwR1ZNdmpEVTRKTUxt
            amM3UW5MUzVUalRzcjFtdkJCeGFXWWcvaFg0ClVhSlB1TGNjVkQ0WUp0SkYzSWgy
            a0tteEdTSFlFbkJ4YldGbGwzMDdyOXcKLS0tIG94STIxSnJIbU1nbGViUGpqNFk4
            YlNkai80WGpUWDd5RjZrNm1scTNIQzgKD+ZtQPf0+AA4TCzAnWdUnzScrXrph7Zz
            deZgZpUZpHAXKhFsAmu8a1VNWdaRzSevGmwAJ28/gM9MmEF9kkKsXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T15:09:24Z"
    mac: ENC[AES256_GCM,data:ouqLttkf2NUDuYa5+gjz0zHAvBQ/vvwcbWe/dHytRLx+FWmsBKTSr/7oz9xVeGx6ky5yCdHQSJILXrJ+goSH9Gr1Zdh+JM+0YdMsSzyzWRk3iu4gQqf/BgI6MMCriGabAt1SgZPlTo7VLAs6Xb7GZdnqY5IvQUQ64VIfhgMaWEU=,iv:UTyyKD2VAtNr04IBsMD82hldK8TbNJ0Z2Te4Htw5T2Y=,tag:SQW5NKQGs0MIM+d0H1xxKw==,type:str]
    version: 3.13.3
