apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-linstor
  labels:
    app: prowlarr
    storage-migration: prowlarr-linstor-canonical-2026-09
    storage-migration-phase: cutover-complete
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor
  dataSource:
    name: prowlarr-data-to-canonical
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  resources:
    requests:
      storage: 1Gi
