apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-pvc-prowlarr-0-v2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi
