apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/media/reiverr
  - secret.yaml
  - snapshot-canonical.yaml
  - persistence-canonical.yaml

patches:
  - path: deployment-canonical.yaml
