apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reiverr-config-linstor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: linstor
  dataSource:
    name: reiverr-config-to-canonical
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reiverr-plugins-linstor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: linstor
  dataSource:
    name: reiverr-plugins-to-canonical
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
