apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reiverr-config-triple
  annotations:
    storage-migration.source-pvc: reiverr-config-pvc-reiverr-0
    storage-migration.phase: cutover-complete
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor-final-triple
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reiverr-plugins-triple
  annotations:
    storage-migration.source-pvc: reiverr-plugins-pvc-reiverr-0
    storage-migration.phase: cutover-complete
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor-final-triple
  resources:
    requests:
      storage: 1Gi
