apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reiverr-config-resized
  annotations:
    storage-migration.source-pvc: reiverr-config-pvc-reiverr-0
    storage-migration.phase: prepare
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reiverr-plugins-resized
  annotations:
    storage-migration.source-pvc: reiverr-plugins-pvc-reiverr-0
    storage-migration.phase: prepare
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
