apiVersion: v1
kind: Secret
metadata:
    name: gitlab-runner-token
    namespace: gitlab-runners
type: Opaque
stringData:
    runner-token: ENC[AES256_GCM,data:3SNn4Iy53dMWYZnqErK4YyAPaguHFhx+mY9BnGbMMna3TekfVxTxMQF3CjQO/pU=,iv:6avwhDD9vCMcS7wbn1JhyguHVjAkwDX45y6gFf5CdeQ=,tag:zAFVKGbueY0Zr0vwJGnKIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4K3hOSTg2eUlBUHIwMXhk
            SUJ6QjlQMDVRQkhtbDJjcjB1MWt4cDloeUZ3CmN3Z0orYk9XRk9ETjdURnA0WDdp
            VHgvbUdNUEREeWtoVnhocXNzUlBKM3MKLS0tIEE5ZXdVMHl1V28xb1ZScEVDVk9S
            ZDVUMUFGN2lPSlNKQ3R0N3JtdUR5dXcKqQ5dWKk53PykSCsxPtqUf88ArJK9cqwD
            hW0bz3AsN7U7KpCest2U8516HRmlI0MWBIgp2W0spWYKGGhgtXUkMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T17:14:12Z"
    mac: ENC[AES256_GCM,data:TELNS2vIooPC2w4HrGLP7FrX9ykrtxYQRGnZJOyMD0ivtGudsLPzAkEEvQZSLiGvWy79JnyzxBLfMck89xknMrOZWqEzWk7rt4OqyGSgSm6MrdO2GgkQOKTnoIe3glR3xEmrsbA3Owaqeb/kR4VDAl4TtqEOTkiyYAfoS7DlqDI=,iv:7UcblNzxIM4ggTi62gbRFShWO0ZTz0VAUJ1WPcBESoA=,tag:C6/S/isnZKrHETUMFDTGqw==,type:str]
    version: 3.13.1
