apiVersion: v1
kind: Secret
metadata:
    name: gitlab-runner-token
    namespace: gitlab-runners
type: Opaque
stringData:
    runner-token: ENC[AES256_GCM,data:AHUUkzQgjQg+/VdWbtsYXD1kfZhXkLde22Odj9CBxvPocg==,iv:wqcNB0QEi5zwPJxzNYxaJAMaMe8qvOxCqgk+sSKxVEQ=,tag:jC6dZyKfyxlc1gR27ilTVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMjFDQk5DTjZmY0VNSllI
            dUYveDhHRW9Mb2ZaalBOYkltTUE0SEh4SG5RCmhIRFJPNXk0K2dmYVg0QVV2Z3Yv
            N0JqbkI5NkhreGVidWVvbVhrbm1oRFEKLS0tIEJkUnlrY0h6YnVxcU8zWHJ0RUJW
            WkMxSzB4U1BTSmpLVFZLMVVUbkRYWUkKUSNi+gn59XfAo0wzcWLVJsdBLSlnk0rP
            3mNo+bYFPWKLic//Yw0LT+/V0mUi1xxDF7bX/FpQ/aL2yCFI+xmo+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T20:21:45Z"
    mac: ENC[AES256_GCM,data:ZTDZRPv3Zpib7lAwWAlqzfMhX85Yg9YmtHuZ/+yJmuznDgdDUvAYeapdUlNnws/CW7LdHJc7LMwrmuh4pftVH53NMkPfff+VNJv2+cNsROXYOMTHQ/oMuoGTknSAFwviv9tVCq0tksNjvxyQ4sinNmYhuzLG5wNK8T3eJpBeFig=,iv:IN95EbOS9EBTlxr47DiW472nGPGEBTkFj9Pld6kftNM=,tag:rsAk8OPrfoEqwnm5Kvko8g==,type:str]
    version: 3.13.1
