apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-triple
  annotations:
    storage-migration.source-pvc: sonarr-4-config-resized
    storage-migration.phase: copy-target
  labels:
    app: sonarr-4
    storage-migration: sonarr-4-linstor-final-2026-09
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor-final-triple
  resources:
    requests:
      storage: 1Gi
