apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: checkrr-config-linstor-v5
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: linstor
