apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models
  labels:
    app: ollama
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linstor-final
  resources:
    requests:
      storage: 10Gi
