apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-final
  labels:
    app: radarr-8
    storage-migration: radarr-8-linstor-final-2026-09
    storage-migration-phase: final-active
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor-final
  resources:
    requests:
      storage: 2Gi
