apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: config-recovery-20260923
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  volumeSnapshotClassName: linstor-snapshot
  source:
    persistentVolumeClaimName: sonarr-2-config-triple
