apiVersion: v1
kind: Secret
metadata:
    name: shared-postgres-superuser
    namespace: cnpg-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:8l8HS0wDQgU=,iv:zvTN3g9zJiv3YXEF+a5cZYax+r7JZgdk+KzCPXeH1t8=,tag:6VOohm9f5NiOWJtEsDSlyA==,type:str]
    password: ENC[AES256_GCM,data:ViVE5l/MBzix3DQmF1Sr/KyZGHAfLRi6JHfevfZzU7E=,iv:eVSvEGAfzzRdeEY35CasQGFn24oA0SCUNUQ+N190Dug=,tag:j2aVjrPX6uxyiLPQKw/ogg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeXlNUWVDVi9YbDJmeHE1
            djI4OVdaSUdYVzNTMmdCWUFEVlVBdFhNeXpFCmFNb3NiOVlEUlIzRmprZktSQVNV
            V3lVL0hRdWJ6QVc0T251TThscW9KcFUKLS0tIFppdXZvUFlxNktKUUVHR3B5TEhY
            b2RUeUc1QU13TnROU0hJM1JUaVB2THMKYmuJXI6KNWV4C3JP0NnkzmHo0Sy1h2Vh
            sQujQYYHMaW3hxeaQDIj/qORNciypPX9N9MTFVvUA1ubm75kHnyHGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T22:31:17Z"
    mac: ENC[AES256_GCM,data:9RTZL1W9fyY9VjlvH/tkNtBKXh/fuAZcyErv+me2tymopxw3+xk8jSY/2CX8fDFQTUJ0xYq/DfqtplRasUpCCvJJF2X5EVfgSrvTzj9D7Cbu2Nwvg0DPpsjJMecF34Rr/pSxAdLjug+ILVYWzFGrnMSaBsiJXUVrWBy+At9AZhQ=,iv:NqM/TxECsqRYRvMKQuOMWg1rNcDp9x8InRyvmKlvncQ=,tag:cNN0xXfqd6X+9elnzcWNDA==,type:str]
    version: 3.13.3
