apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: "0 1 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: artifactory.local.hejsan.xyz/docker/renovate/renovate:39.117.2@sha256:037b176f1cf152930f7869dcf8f969a323bd8df3dfc16d59a96346843d010163
              volumeMounts:
                - mountPath: /usr/src/app/
                  name: config
              envFrom:
                - secretRef:
                    name: renovate-env-secrets
          resources:
            limits:
              memory: 1000Mi
              cpu: "1"
            requests:
              memory: 700Mi
              cpu: "0.4"
          restartPolicy: Never
          volumes:
            - name: config
              configMap:
                defaultMode: 420
                name: renovate-bot-config
