apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: "0 1 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: artifactory.local.hejsan.xyz/docker/renovate/renovate:39.74.1@sha256:0eb8fe91ce69aee886d036909c7f5b0633f5f074c43fa75b7396250f57a7fbc1
              volumeMounts:
                - mountPath: /usr/src/app/
                  name: config
              envFrom:
                - secretRef:
                    name: renovate-env-secrets
          resources:
            limits:
              memory: 1000Mi
              cpu: "1"
            requests:
              memory: 700Mi
              cpu: "0.4"
          restartPolicy: Never
          volumes:
            - name: config
              configMap:
                defaultMode: 420
                name: renovate-bot-config
