apiVersion: v1
kind: Secret
metadata:
    name: renovate-env-secrets
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:KrixPoM842IlMMm9Md5w+QB7ovSx+9JwwJ8=,iv:qIcg6xW0rPRUjz4unrObsoyoFGnmE1a27WQtquDMj4s=,tag:1OgLNcsmNh33rmwsZtlXhA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Z1QyQTI5ZlNsQi9ibWNr
            TytLOG5CSXoxRFpSN2liNGVBVzZta2plWndZCmxhV2NCM2Rxbk5WcnhHZjFNQWhw
            bmVmVE5NK0xaRmZIekIyUU9qUVpQSjgKLS0tIEhHTzdtd0JmRzgvRjZIRURzb0Ev
            YlVHY2VwNTlreTFzc2ZkaTFHemFCNDgKESSrJa/WMvis21gG2SS+Nqo2zrbV4nOb
            Hvm/C8DFdER8fBBd1TKRydAU3zd5XbnHmeRx1kqRKEG1iKERWahbeQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T08:24:40Z"
    mac: ENC[AES256_GCM,data:DaPuMvfWB38j7VhVFITNlCUiNsucuVC7Y9M1Auigx68hFtDQ4vvyZj9O5UZIa6bn7VRy2+IvSgoNfZamqp32qty4LH6/GEakQPqskbqeIw7wYrV0bvu1TArpSvoUXLOEsNQIVDDp8S1wxFAk/R6xDmVzDfgYZV1H2Jlqqjx3S0M=,iv:Dvh3E7eT0zfuSkGdI1UehPspIf/fI6yux3ndkR5kF/k=,tag:hmlrggez0NfJ6px6HyBtWA==,type:str]
    version: 3.13.1
