apiVersion: v1
kind: Secret
metadata:
    name: renovate-env-secrets
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:SxOslIDbYasnjEqDS3kjt4pET9v9vQbgLmI=,iv:11c0L2q5gYE0K1T+ETTSRR+oTJPeEmgCus6xDDymSGo=,tag:29lwALBE3/PkZKzSliiXsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbktSSEpYVVArMWVqdCt6
            dzkyRlhtNU1OdTBwN202K3k4SXYxUUFiKzFjCnNtZG5ZdnUva1BHTCttUzNqQ3dn
            OFpObW9KR1BYVjJOOGhBaEVWUVhXRVkKLS0tIHZueUxMTnhxQzQvcUx4V2Q4a1Zq
            eVkwZC9wSlBrcVZQZjVRWnBDRHcvODQKFMf/wa50iMHQkRFlbakQIXDbudm0LXXD
            QadE2+8M8kf9mRVrWeBMUQSeDkA3pIUmXXS7Z0fJYylv0rKmlyOEWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T19:12:39Z"
    mac: ENC[AES256_GCM,data:XvwabT1p3K0uvEmJNt/CDC9leBXEom01xTNo8jibGnCP93ynXlju4gQe138QukKYJMqZ5TbVpkW3LvaFLwjW3tgyH5KspIsK8ZV+bd0a+FQdo9Q/9vFfjlhUWPp011flu3ytm4K0c+7UzFr2ojGQno7p0fXx6fy7vvZJJmhrtdk=,iv:LSqjdtKQIASGLaUKZK9HRZu98gkBrYgv4e6XTCUiF2U=,tag:DLOLH+sYjFc+ncl+8k5cHQ==,type:str]
    version: 3.13.1
