apiVersion: v1
kind: Secret
metadata:
    name: renovate-env-secrets
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:WfnnxA2CtxCo/NuI0tJ2PY55K7i8EEG3+bg=,iv:lslopV2MBDS1zmSFgoDdsoO1R4eiiOvt1M5Ew7IPMEE=,tag:NSbcDQuNCftCyrMVnJnHSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bkR3NGlYMXM5R1AyZ28w
            bFVGZ2lKTktoU0NqUVAwK1NUYnF2aTVmR1RVCmpoQmlWblk4L2tiNzJlRWtFaHFa
            alRMeW9WT29EWVRtRkVvSU1QVDlydkEKLS0tIEF5dlp4NXpqSlFWYld2VkUwbzZH
            RS80NTJWeDg2OXRDUjJzK1l1ZW1jaW8KzQALMNkHu2Qdm6x0xKSVI3ZQm311nu3T
            bMmy8WVP4YeC9Kio2Sw5NYbYi+Ll/PHhIuzpyCI0RQc5yQIb/t1nUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T08:56:32Z"
    mac: ENC[AES256_GCM,data:IDhakpyGl4QRfVud2kGaOcORbkxf1OdsfbMR6qfnSaO0AsG+GOB1MyjZAaNiBfBu162S94fciwPkGs7Q3y0fqrX5IAhqwAeXsNi6msEHzhEQu8cXcqSMZZzGOuzdnPj/yCiVaFxVgKyDAiC9U+A9j1hOBGqlNtXsdJBpJsGQ09w=,iv:436Lz9o5rH5C4//Jx4aXwtc57rf3l/p9z3OlnEZX6sw=,tag:Fhalrji34vstMuIau3Resg==,type:str]
    version: 3.13.3