---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-storage
  namespace: flux-system
spec:
  suspend: false
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/storage
  prune: false
  deletionPolicy: Orphan
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-ops
  namespace: flux-system
spec:
  suspend: false
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/ops
  prune: false
  deletionPolicy: Orphan
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-observability
  namespace: flux-system
spec:
  suspend: false
  interval: 10m
  retryInterval: 1m
  timeout: 20m
  dependsOn:
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/observability
  prune: false
  deletionPolicy: Orphan
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-media-foundation
  namespace: flux-system
spec:
  suspend: false
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: apps-storage
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/media/foundation
  prune: false
  deletionPolicy: Orphan
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-media-download
  namespace: flux-system
spec:
  suspend: false
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  dependsOn:
    - name: apps-media-foundation
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/media/download
  prune: false
  deletionPolicy: Orphan
  wait: false
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: arr-dashboard
      namespace: media
    - apiVersion: apps/v1
      kind: Deployment
      name: bazarr
      namespace: media
    - apiVersion: apps/v1
      kind: Deployment
      name: checkrr
      namespace: media
    - apiVersion: apps/v1
      kind: Deployment
      name: prowlarr
      namespace: media
    - apiVersion: apps/v1
      kind: Deployment
      name: reiverr
      namespace: media
    - apiVersion: apps/v1
      kind: Deployment
      name: seerr
      namespace: media
    - apiVersion: apps/v1
      kind: Deployment
      name: transmission
      namespace: media
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      TRANSMISSION_PEER_IP: "192.168.1.184"
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-media-arr
  namespace: flux-system
spec:
  suspend: true
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  dependsOn:
    - name: apps-media-foundation
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/media/arr
  prune: false
  deletionPolicy: Orphan
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-media-playback
  namespace: flux-system
spec:
  suspend: false
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  dependsOn:
    - name: apps-media-foundation
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/media/playback
  prune: false
  deletionPolicy: Orphan
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-photos
  namespace: flux-system
spec:
  suspend: true
  interval: 10m
  retryInterval: 1m
  timeout: 15m
  dependsOn:
    - name: apps-storage
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/photos
  prune: false
  deletionPolicy: Orphan
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-gitlab
  namespace: flux-system
spec:
  suspend: true
  interval: 10m
  retryInterval: 1m
  timeout: 30m
  dependsOn:
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/developer-platform/gitlab
  prune: false
  deletionPolicy: Orphan
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-artifacts
  namespace: flux-system
spec:
  suspend: true
  interval: 10m
  retryInterval: 1m
  timeout: 30m
  dependsOn:
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/developer-platform/artifacts
  prune: false
  deletionPolicy: Orphan
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-services
  namespace: flux-system
spec:
  suspend: true
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  dependsOn:
    - name: apps-storage
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/services
  prune: false
  deletionPolicy: Orphan
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-home
  namespace: flux-system
spec:
  suspend: true
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  dependsOn:
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/home
  prune: false
  deletionPolicy: Orphan
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
