apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/artifactory
  - ../../artifactory
  - postgresql-canonical.yaml

components:
  - ../../components/prune-protection
