apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: odysseus

resources:
  - namespace.yaml
  - configmap.yaml
  - default-app-config.yaml
  - pvc.yaml
  - db-claim.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
