apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odysseus-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ${STORAGE_CLASS}
