apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${STORAGE_CLASS}
  resources:
    requests:
      storage: 1Gi
