apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config-triple
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linstor-final-triple
  resources:
    requests:
      storage: 1Gi
