apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config-final
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linstor-final
  resources:
    requests:
      storage: 1Gi
