apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../apps/base/media/transmission
  - snapshot-canonical.yaml
  - persistence-canonical.yaml

patches:
  - path: deployment-patch.yaml
  - path: peer-service-patch.yaml
