apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config-linstor-v3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: linstor
