apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: config-recovery-20260923
spec:
  volumeSnapshotClassName: linstor-snapshot
  source:
    persistentVolumeClaimName: radarr-4-config-triple
