apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.yaml
  - linstor-passphrase.yaml
  - satellite-network.yaml
  - storage-pool.yaml
  - pilot-storage-pool.yaml
  - storage-class.yaml
  - pilot-storage-class.yaml
  - rustfs-credentials.yaml
  - rustfs-remote-reconcile.yaml
  - radarr10-backup-schedule-reconcile.yaml
  - snapshot-class.yaml
  - node-prerequisites.yaml
