apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: pilot-lvm-thin-storage
spec:
  nodeAffinity:
    nodeSelectorTerms:
      - matchExpressions:
          - key: storage.josmase.io/linstor-pilot
            operator: In
            values:
              - "true"
  storagePools:
    - name: linstor-pilot
      lvmThinPool:
        volumeGroup: linstor_pilot_vg
        thinPool: linstor_pilot_thin

