apiVersion: v1
kind: Secret
metadata:
    name: linstor-rustfs-credentials
    namespace: piraeus-datastore
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:QoXM7R0Lc5LziiZQY5dWePc0dUC6Y2HMqqowZeG26TKhw200gg84ZQ==,iv:gYcgzwtvVwkQc6CUTM6Cx/ai0wBpQZ6lW21gt6sLXH0=,tag:0RYxUy2RQUGz/sTJFz6REg==,type:str]
    secretKey: ENC[AES256_GCM,data:vmh4cWyhA8y2XjSK4/t3A3a4YqSU8jg5Ldj3xiQAbnAzNLce0J20DPIUzkWNaZKEw1YcN2+YDLcEfa5hP/td/Q==,iv:JVL8yhfeT08/GYuB1HwpeW6+MTOyLF90ow4KF9mQNHQ=,tag:43+9gyxmPbNYSGw7Ne6Nkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYjE4WWo3ditad2xDQWN4
            SUxKZ0c4UFpZM1pkb3FVaUZaNUthM0hXMlI0CmUyM1lCZi8rTUw0Q3g1bzdlcFc0
            S3BQaUlGZUVwTVEwa3M1ejhHQUZyZWcKLS0tIFF0VllUQ2VzdzdSbmVZNS9qeXpG
            Y3lvd1Z5U3l1c3EzV3V0dkxzaG5mK0EKKHgFHy3wqIOPaBy73zCayrrdblJ8rSUs
            0ffMCKSP077ZKZk8CoVpL40pl5w6uyh8WgbakgDl2/u8EnZQ/woIiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T08:03:41Z"
    mac: ENC[AES256_GCM,data:EgO4nftlPOP0PkWik8ctwNuPfhz1OpyxZU/9m3mDTIaXCeHGBh5v0lFgHoQGQ7jH4pmM15JdEHTK+xb3osXQieRVIknpKUVCf5roRIUHp1hpuKC+1ZKzxhDL7zKAyo5fcURN7X5GibrCZY0rG/6EXCxaw6u8vIzOPtryFEcEp2M=,iv:G4W83+qiHyunnThbQdScTwqN72flGPXJlGKlwDNCuNs=,tag:bz2OkfPGMH7FXijGiqGjpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
