apiVersion: v1
kind: Secret
metadata:
    name: linstor-rustfs-credentials
    namespace: piraeus-datastore
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:0wzssG24geMlXOFqo7RrA4v02wIzfNjC26zzxcHJYZ8=,iv:gWJWOiPZqYfY+SoBvem2H5Qze4vhhp2c8AVW1IW7HaE=,tag:eNwMa/q23f9QEsJtrVv08Q==,type:str]
    secretKey: ENC[AES256_GCM,data:K+L0OUXKgU1XhaOAFrcBHWcGfzKqTOysNFCtODz9sTtUVO6si/QScaBoe0BsyCRoaKE6XE+Qb+3EMS6upyFMNA==,iv:RV6Kl8aVLxaCXpgl9iDv6d1MHXsSEyHpt1sZ69wtb94=,tag:IpjUR5rzopoBTZt+FEuFBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVnk5WFlmaU5XdEsvRWM4
            UlJkVGJuUm83cExXQUxhOXBTL2RETCtCRnhZCjhqUWE5enI1cmN1ZE9xdmtzZmhq
            NEx4S09nWndvbmV4ZmRxeWt5L0h2TXcKLS0tIFZqaVluYlNZK0Z3eVNRbDNjWHdZ
            OXpaOGtqUER6MUFHL001UlMxVm5pb2sK2exM6f7wAvzk+bsR55it0SysGsgOlm+m
            1IPRFtBHbdH/XMVBCv5kH5JccY3cdiF470eftLGcXZ51xp7SWrONdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T07:52:34Z"
    mac: ENC[AES256_GCM,data:HV5DjqHVwlFq8NM34VIqYgMUwimdUqyjOI5ErUPBduRLwbnAVMsp4FFr7xZVWTeLKg0/w3ew68I+HWtRhelKy0XoYmpfbnScypMwoflshygBBAXqwUbIcch88FoTS7K5ZFnEX3Fp0JFqnoAE2Vpmt9ao3b3eaJlhXBZaIbSzBb0=,iv:xSb0CWppsr+eCEd0FabG5q1fCMl0nS2mwsXs6M72+WQ=,tag:TXpeI7vm738z8sTG0KDmNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1

