apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustdesk-data
  labels:
    app.kubernetes.io/name: rustdesk
    app.kubernetes.io/component: data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linstor
  resources:
    requests:
      storage: 1Gi
