apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: checkrr-config-linstor
  annotations:
    storage-migration.source-pvc: checkrr-config-pvc-checkrr-0-resized
    storage-migration.phase: copy-target
  labels:
    app: checkrr
    storage-migration: checkrr-linstor-final-2026-09
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor-final
  resources:
    requests:
      storage: 1Gi
