apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: checkrr-data-to-canonical
  labels:
    app: checkrr
    storage-migration: checkrr-linstor-canonical-2026-09
spec:
  volumeSnapshotClassName: linstor-snapshot
  source:
    persistentVolumeClaimName: checkrr-config-triple
