---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: growlog-media-data-linstor
  labels:
    app: media
spec:
  storageClassName: linstor
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
