---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data-triple
  labels:
    app: media
spec:
  storageClassName: linstor-final-triple
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
