---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data
  labels:
    app: media
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
