apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: "0 1 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: artifactory.local.hejsan.xyz/docker/renovate/renovate:39.242.1
              volumeMounts:
                - mountPath: /usr/src/app/
                  name: config
              envFrom:
                - secretRef:
                    name: renovate-env-secrets
              env:
                - name: NODE_OPTIONS
                  value: "--max-old-space-size=1536"
              resources:
                limits:
                  memory: 2Gi
                  cpu: "1"
                requests:
                  memory: 1Gi
                  cpu: "0.4"
          restartPolicy: Never
          volumes:
            - name: config
              configMap:
                defaultMode: 420
                name: renovate-bot-config
