apiVersion: batch/v1
kind: CronJob
metadata:
  name: configarr
spec:
  suspend: false
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: configarr
        spec:
          restartPolicy: Never
          containers:
            - name: configarr
              image: ghcr.io/raydak-labs/configarr:1.30.2-alpine3.22@sha256:14eb335a4feeea84f5c1e3ac185b0932b192cfeef89b920b7e2df11bebf3bbe0
              imagePullPolicy: IfNotPresent
              env:
                - name: DRY_RUN
                  value: "true"
              envFrom:
                - secretRef:
                    name: configarr-env
              volumeMounts:
                - name: config
                  mountPath: /app/config/config.yml
                  subPath: config.yml
          volumes:
            - name: config
              configMap:
                name: configarr
