apiVersion: batch/v1
kind: CronJob
metadata:
  name: configarr
spec:
  suspend: false
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: configarr
        spec:
          restartPolicy: Never
          containers:
            - name: configarr
              image: ghcr.io/raydak-labs/configarr:1.32.0-alpine3.22@sha256:ad4e9ac27d659fc30f69d1c9bab719019c70fd0d5ceda85367a8f723d7c99c91
              imagePullPolicy: IfNotPresent
              env:
                - name: DRY_RUN
                  value: "true"
              envFrom:
                - secretRef:
                    name: configarr-env
              volumeMounts:
                - name: config
                  mountPath: /app/config/config.yml
                  subPath: config.yml
          volumes:
            - name: config
              configMap:
                name: configarr
