apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - ../sonarr/sonarr-2
  - ../sonarr/sonarr-6
  - configmap.yaml
  - cronjob.yaml
  - prowlarr-key-repair-job.yaml
  - secret.yaml
