apiVersion: v1
kind: Secret
metadata:
    name: configarr-env
    namespace: media
stringData:
    PROWLARR_API_KEY: ENC[AES256_GCM,data:J+pELY6OT9x789bI5g8haYghE4ShNq8LRlg/IsRkFmk=,iv:cx743BxgXN/P0I4KlrgsJZvj9DbY9OrCSWgU/p7L5eo=,tag:uwcFes/9mGoWqdZsok/AiA==,type:str]
    SONARR_1_API_KEY: ENC[AES256_GCM,data:t2cczqqxleQOo9GX6bJIuU5OxZQ0nGRpbjKDJ5Q7Fxw=,iv:boA5igi7zj73p9AgqLbns5sq1VPBMroLBSqstfU+bVY=,tag:F1eGbzQugaYsm5QcL2zEEg==,type:str]
    SONARR_2_API_KEY: ENC[AES256_GCM,data:eJe0Bk5scxOpZJox8WJS9kgqE/WkkEXZGQShUi5nDPg=,iv:oYeBRWwFwQhWKqgHgm6LThPZJ8lb6DvxuReQnBevew0=,tag:uSpRFXVgN4RTyLjGTLm22A==,type:str]
    SONARR_3_API_KEY: ENC[AES256_GCM,data:G6p+dg2Fm9YRpcshaSKR4Ledf80W8/aY63n7rSmVYJA=,iv:EA3QWvlPWxhyhIfW9LdP/d1h8src2kc+wEsSU8NbtGM=,tag:SVoy8Ks8iTK1Z4zlgUa0qA==,type:str]
    SONARR_4_API_KEY: ENC[AES256_GCM,data:W0VfTdbLGzGeyx9/2zk1DZcn7P9v8fmvYTAzfQazq2s=,iv:7+TIIOJE0qDBPJP6t3TtlJSfGUkTldipB0eaQi2gyFI=,tag:O/jV0hlhVYP2IJntxwaYeA==,type:str]
    SONARR_5_API_KEY: ENC[AES256_GCM,data:NHTAfAF5uneqRObRtxSYFbvoXsYZSAEKKcB6kZMuIpI=,iv:MH+/C/RbI2k3JVQqgNPevl2hnlVkqBGcCiFuJUQtjRY=,tag:b98HZvB7w3mG2TjkCWt/5A==,type:str]
    SONARR_6_API_KEY: ENC[AES256_GCM,data:Do9dELPGXkm3YYGnZ+A5nKXVLLvczRgNHV7rKLD78yQ=,iv:fNMY9QRjtEg5wGwr/rchgB5mM6PjtSG+zvjZwvQwhwA=,tag:3aJ+ot15PuJHzF7CZjmvGQ==,type:str]
    RADARR_1_API_KEY: ENC[AES256_GCM,data:jI++NR/iim9AL1kUtNCbANQXxGbbue0oY1owHg5751c=,iv:02Czq/zOA/+9niVImtiF8+A1yO2cJ2bYquohXJ3Wy9w=,tag:grQmu4ScuERNN+GV0CHHsg==,type:str]
    RADARR_2_API_KEY: ENC[AES256_GCM,data:Say3Ho6ZTE4Qi+ijvheWpvMwiLx+95W3MIeW+ivJiVM=,iv:hLBLP5VrC6vJMojocr1bFVnQJ54tw8ZlM4nIvXxA8OQ=,tag:CozUyNnysWeMBrW3PEZefw==,type:str]
    RADARR_3_API_KEY: ENC[AES256_GCM,data:wdkQ4URuFl0oype2zxbT+Btz2QcoVTP2w8eyIYbsmhA=,iv:Tx6F8idzZNVqtMdkKBi5AjmuwAMc2bi8KtItm0Lsdhs=,tag:/hKe/UbTi1JILCpikYZLcA==,type:str]
    RADARR_4_API_KEY: ENC[AES256_GCM,data:yvhoU9aCJyxccLhMRU7OO/WOR1BrRnAyZvVrwHeosQw=,iv:UrjEn6gZnsTqm4csQn//QsheeMzBfGak2rGyrHF8ecE=,tag:j1Sv3QMAaAZv9Uu8FYocPg==,type:str]
    RADARR_5_API_KEY: ENC[AES256_GCM,data:5TWdX/MRIkrXjUaEcOFjk79GmbtfuJmUw1HTvQdlHBE=,iv:mA1ZgFexGGQqOPsrfn24XopKLi0OohNE9k7189PCXWw=,tag:P0Rk0F8C6gl1VykUK47jJg==,type:str]
    RADARR_6_API_KEY: ENC[AES256_GCM,data:tTDpI5o5yR0XebeHw6rfohiicRYtUkzffB2+9xKXBr0=,iv:avglzJC/j2yh19OFazuxSRKILEf4T/5lKyAzLk5P+ic=,tag:5tlALkPMkhZw9z+8NC+g5Q==,type:str]
    RADARR_7_API_KEY: ENC[AES256_GCM,data:GXIMVerSBOxcsWzBh1buSPLroz4Hm/C3/J0c9KuUayE=,iv:FLTZb7Cf6Yc5D5TqN0bCjp4v4SRw3hbAYfuE6vqdbXs=,tag:fz8huBzkz5yWW7YKOqx86g==,type:str]
    RADARR_8_API_KEY: ENC[AES256_GCM,data:hMV1m26yXkBSJPSlDtBmzOcFYRsmBCSeYUjrezNFm78=,iv:VXX/VDwLNpqcRQGMZFYplgyMYIz1FDuA1qLuR7WKO20=,tag:n5q0lXwd+tmA9G6GIciivA==,type:str]
    RADARR_9_API_KEY: ENC[AES256_GCM,data:a/akcR+TfWMy8AICKmPX3GYe0lAfcEvUsl4incUyuMo=,iv:mto7ud9my/Jug1EFzBtvlW1D28UnlUHIu8NkOjWGmQU=,tag:+7D1hxlRft4zgQNvKcxHOw==,type:str]
    RADARR_10_API_KEY: ENC[AES256_GCM,data:8cW5YxnRnh9OOtyAhN5tiaJFs/06z9JC9U1bQb6KWHM=,iv:3pXxHcVdJs0XykZjL26nxWB7t/ENwqGNu9D4pBwdML4=,tag:stVNPFcs6N7kBbBa5aWzjg==,type:str]
    RADARR_11_API_KEY: ENC[AES256_GCM,data:rNCLbmJqiphsHZVGEwzPMEqnvXTexqOG1uxRf5sFxc4=,iv:1QfUq0GDn4rs1kOwac3bkkFNNit9ovs4f6drzYTwJAY=,tag:85A4taxNhffJJrU9UIn9WQ==,type:str]
    RADARR_12_API_KEY: ENC[AES256_GCM,data:N96FA3Me+I12bcjMGej8SWezwGJp3x4wL4UkVBG+rRE=,iv:M68ZRvZd4pZ5wSDIRdrjBFPLKbTdDpI4UvrRBmGmiOM=,tag:43f/VRf0SSvMvsmLeSAxUw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxakh2dVhnSjVONG9NRS9K
            S21zMTVvSnVud2paZVYzTFl0SGEyRDNKQ2dRCmdDSW5zb3lMQVlMV0RVNGxTOENl
            TlNwSkV1SU5uUjM2V3cwMTNTdm9GdTgKLS0tIEsraUl2NHdxbWxrMHppMXA5anYw
            bDhtb05sMEJtRmJsRUVKY3VrRCtCVjQKo7xgaF2nj9LcDjEGM4M8UL7oUkjgaPEE
            sZqTQbnHzQE0DYQ19DJ4+QQmxpBvcEahWuy8Pnd+8/gQE5OqJd+FPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T23:54:54Z"
    mac: ENC[AES256_GCM,data:UX4vX4Lmf8y4D4S2q9QRXkjYNZMX3IaA4hDgu7u2XSQUkIrz+F8T4kphxMtMIpmBrDvGPgmzGj6esh8uFvOBJV3CQrFwDyDpZeVOOO0+8wWmbX+vazFVnk5Mga5hl4BZVFjGmRHKJjYqa996LVoVLMxi+995KLjQZ9qnpYjm2NY=,iv:3tzUkBWepKmC4goKyOjUPS4oOcFSkEm8ltrjeSQGTfc=,tag:oDvXdmoDznvFutaOz4uVxQ==,type:str]
    version: 3.13.3
