apiVersion: v1
kind: Secret
metadata:
    name: configarr-env
    namespace: media
stringData:
    PROWLARR_API_KEY: ENC[AES256_GCM,data:eSTBk6MSjFWAlMXgr6g30PSkSMQI3fa8XLSueoroGLI=,iv:0mM6eJer3kEdaTjFIzOerYvGrY3/4zv0oYzvPuKpgTo=,tag:i+Z+gE0Y37t4PhvLaukJ3w==,type:str]
    SONARR_2_API_KEY: ENC[AES256_GCM,data:Pfi/0qSAwjOoExIRHnx90FjoJtj4gdqUq1d3bFiWXuM=,iv:pVsvLsV1ix/gIMMl36eXy31/WuR6omidqtbcJe1f+Tc=,tag:ufe6KRlWcBgfAhevEtRgNg==,type:str]
    SONARR_6_API_KEY: ENC[AES256_GCM,data:/G+wnXIm1+ZaFheehmy7gtHzJE4XDpgZNfqIHqN1+iQ=,iv:nE50LWjJihqwnNrLrdyuJ8x86zEoDNEBNJvXi0sjMPk=,tag:jG2wW/z5/Eg2thbepkuh1Q==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQTNnZ3FmUGpHMDJNNmVG
            TkducDNRZ2JoK3U1WXdjSHNnYTBPYVNzbGo0CnRRS2ZBMk42NlVodno3RHVGZmdw
            OHUvNnZ4N0x6NGg1dzJZeEtDSGM1UFUKLS0tIHhmRHcvTkZCeE1yNktVY3RyZ0NR
            Y2FDUlAxM3lkVnNnblBCTy81a2MyZDgKRysnQyUEEG7zf1yqXYKZp5hNj3O3Lq26
            sGHC8kgVJKuw4dyCed3RgXwEFB6DzHZD1bKOIoT588v0fBzcO4tXTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T22:15:30Z"
    mac: ENC[AES256_GCM,data:UevzWJLn7WFRhqIo+SEAvbElvK6iYcL8JXIkuvEd1OhQYEG/02NX/qve02y5nj6y5qItBlw0aJuI+CJBGVlU3vfBXO24fagcTYgAvH1lcmmbRFzGV54j86PoPqa38rK7SFZ8qBVunw/qbseMvMcLIUzhpDctwNF0Dr3wo2SFd+8=,iv:v+SoBAUV51s76RgcO3v96OctxE7XgN6OCE5s65RRjn0=,tag:fJEyPxQweX/XoJMzqa9arg==,type:str]
    version: 3.13.3
