apiVersion: v1
kind: Secret
metadata:
    name: configarr-env
    namespace: media
stringData:
    PROWLARR_API_KEY: ENC[AES256_GCM,data:HKn3FnwxCdhgPYF0ZRKNb+QWCwG8AMmQ3tPiCbQggi0=,iv:cg2n/A7oQemhXRS37j+lF3dkbWa7E9QP8Mj1D5rKjzE=,tag:7yY/6YP4nk6vnqPxJCucug==,type:str]
    SONARR_1_API_KEY: ENC[AES256_GCM,data:NuehHocXfVgpNJHmDfyjXXrnV86Igun1Lb4gr9aGzz0=,iv:a3tncqJhHQia74Fr3bHTF5Vrfao43965wlH+tryaQ9g=,tag:nES+4luDHBUkix6SaaTzaw==,type:str]
    SONARR_2_API_KEY: ENC[AES256_GCM,data:KUjpbrvqxFCPaTOwFTZm2pFzhU6vqk567G0mYQjzijc=,iv:DHyS/Eeo8gOPz/WwJnHLvUcmomWYkLvX5xJwkX0iQ/I=,tag:T2RdKIaZfbKdKOjJyJCSvg==,type:str]
    SONARR_3_API_KEY: ENC[AES256_GCM,data:KYBPAPOXqokofU8+eecHn2JjnAIn4bZekv7rHKOHnA0=,iv:NEDu/NtTEH4upOOvloDJlVANprjQEp3eraFFMsRWLTU=,tag:Sl9uMRA9RGFdrxfp2PXCvQ==,type:str]
    SONARR_4_API_KEY: ENC[AES256_GCM,data:iqqyVurrJI2Jckyv6vPSCeEIXLl/PfYGQW77UKYf2ZM=,iv:Zw/E7PtO0vIKYYqcOTrr7WxfrfHaEUYFhgldCUe8ZPk=,tag:3+13PaIneFQ+XxJVuNcOvw==,type:str]
    SONARR_5_API_KEY: ENC[AES256_GCM,data:YFSSd/TXoMG2A0PXZgcq/lw4kMiKXfauAEc/CBa9QoE=,iv:BkMArFe9auOmkJNeTa0UG6YHSDSoBKNhsTSJ8L2HQRM=,tag:BqZePiOG3PGXxFJf27cwPw==,type:str]
    SONARR_6_API_KEY: ENC[AES256_GCM,data:tNyrMYzSYhDA/QxZOwfjUlb7mDw+IZi2i4q9s4YkkVw=,iv:rzF1SWDXJcjWelW5pmZnzZnPnxO3GLQFF+CJ+rVopZo=,tag:VJIpQhlFJxshstTiGLCoUQ==,type:str]
    RADARR_1_API_KEY: ENC[AES256_GCM,data:pF0QYlZTqDiM2DhHe+jOj4ezzPnQbgCQz5IqZ2cuq4k=,iv:oO1q735Qb7ATotgpcI5FGvWkMkWoJBpkoqneogTGmPQ=,tag:ujgvNzOwcTR3c/M7+cGTVA==,type:str]
    RADARR_2_API_KEY: ENC[AES256_GCM,data:Oa+ZASKADivoLB/ZgjIdnZtpgh5Vo6lDRY7xqmsYI8Q=,iv:ucrkRpACGLrckR8oUmKWUO5zUvj48XlvQDQ5oUwXdqM=,tag:rNwHBZUIkIu6zLJd3u5m2g==,type:str]
    RADARR_3_API_KEY: ENC[AES256_GCM,data:QaTfWL5KxCt0PF5HjaGVAUGsDAgjZHMV5545mFNLugE=,iv:nrAyaSrTOL8mfoFIgZ+HYzsDZg+QyJzFWAyWYeOJlMQ=,tag:NGZw7ul2zMIglYw6cyLjWQ==,type:str]
    RADARR_4_API_KEY: ENC[AES256_GCM,data:6ivwlMkwFkUT3FuGFjkYiU14nUJzrQ3ufus21y38OcY=,iv:7FnmTru0yOLY09ZhEL9PlwrkyeBS7DfbizpGxcgWMoE=,tag:ToLnyCZgrVzrwL4at8/8Aw==,type:str]
    RADARR_5_API_KEY: ENC[AES256_GCM,data:rJW3f6HXEqw1ry7J+0DFhr0JXsX8O4YLi9dED/lx208=,iv:P/Bd1Nvy8yQHrtckbOAOThmat9cTFGE3tGV6J3n/M0w=,tag:/xasB1KKg2B/BQ/Ujn+/Tw==,type:str]
    RADARR_6_API_KEY: ENC[AES256_GCM,data:0gdlf+KE2M6XxsPaHtB8XH9iEDi2z7HUz4ChU+qyi7k=,iv:uROUYf/se3mnNuVA3JsipFyk3lfluaS6de4vYkwbiNo=,tag:oMK4OsVF3/IxXj7U8pNjQA==,type:str]
    RADARR_7_API_KEY: ENC[AES256_GCM,data:Oc+4rBpqn5HZY9CECchISQj47IHhECBbwd9U3LRf4dw=,iv:iCGCAoLVpVQVt/25pGGNUBh3inoP7f6LPyZgs+Qh8MI=,tag:+sRoJifj7fR2xyTV5pMZrA==,type:str]
    RADARR_8_API_KEY: ENC[AES256_GCM,data:3LRUJL00rVgi+1naMGFRocQRFMPKwUcJge7cd4qR9HY=,iv:eTnCsH7YBCrVNjc6A6YWG6bGrMq9LGBfShtsAlTLbt8=,tag:KXe0Lb5qlB9NWxClOqEqzQ==,type:str]
    RADARR_9_API_KEY: ENC[AES256_GCM,data:TYAFJCaia9KaCGOHniI51C0TKUrjDlW0TUsrw7+lk1w=,iv:qpTDgu54Si3nvUINwGLsH3Rb3VOu2PhFEdvd6Sdxk9U=,tag:EGSUBeDqmooCupiBdJ5Tfg==,type:str]
    RADARR_10_API_KEY: ENC[AES256_GCM,data:Nu/jjmTUpjc8iMuR9Oj03mZpQbOfE4miijabtaCM75k=,iv:fqKiNwj+yJR0HvhucwfFd8aVQ49ur7g3DCcHQP0F/JE=,tag:7lVBboydg4Q9B09GdrV3LQ==,type:str]
    RADARR_11_API_KEY: ENC[AES256_GCM,data:xO/OWc/65z3V88ODO7Wdlpgorry+0jv9wJSlRVAdmXA=,iv:Vly0uthQkpsRdrn1pZ2v9T8e3UUS/RndYPv/qC6heos=,tag:C0e6lFunRuwmJaJS5OtEIQ==,type:str]
    RADARR_12_API_KEY: ENC[AES256_GCM,data:7eoDioQJCy9mEimijF1L8d5qLaLn/RUYLqg2CPhpFEo=,iv:cOlIOIv8P99RvFiKrqu3SDUJ+4L9sSGFigJNPMO09SA=,tag:LW19sFzNVKA1Cu+K0+3Ayw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBES3EyQ1ZBbHd1QVk2RjZK
            UzdFYm0wUDhIdGFhejB2NlJCTXNMME1tZnlNCittWWRTbkMzVkpRQ0pSaHJ1bloy
            RFNsZ2ttTjl2M3ZPeUlPZU05YjZsVW8KLS0tIGVvMVBPTlUxdEFBZ2dHMnd5WW1Q
            QnpBQlNzWllDZDZuMmsrTnF4ajJYTTgKWUpQ7Fc2YeRsRGTDBbBWMefa12PGbwpV
            AWXwH9/n7sSyCRPZRzwdKX4Sx/Jirk8yBt29GTTOuHI0PsZv8LhoHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T23:11:13Z"
    mac: ENC[AES256_GCM,data:NHcPQVtjKl6bNDQ+vCzgwUJKMi3Zv8cu8ojXrNoISAWvWRxgYF36a0bF7e1PU3prTqInfqIbJtkVDYZ7N2AcjjC8V4DN6IFM+vCGy4Spe7JzGIX40WhXCjyNOv+HGTikdMMAs1Wkm6rjT4WZcIcX+J7RgQf0iUo/mTT4FG2jSOo=,iv:lS6zkcCfrfGf//jpER38w3MqTfPL5W7E4ZWB3SDfuxg=,tag:2snw/vaFAImMf3AtkesezQ==,type:str]
    version: 3.13.3
