apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-linstor-v2
  labels:
    app: bazarr
    storage-migration: bazarr-linstor-canonical-2026-09
    storage-migration-phase: cutover-complete
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor
  dataSource:
    name: bazarr-data-to-canonical-v2
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  resources:
    requests:
      storage: 1Gi
