# Persistent storage for Gotify.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotify-data-triple
  labels:
    app: gotify
    storage-migration: gotify-data-2026-09
    storage-migration-phase: cutover-complete
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linstor-final-triple
  resources:
    requests:
      storage: 1Gi
