apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: gotify-data-to-canonical
  namespace: monitoring
spec:
  volumeSnapshotClassName: linstor-snapshot
  source:
    persistentVolumeClaimName: gotify-data-triple
