apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-shared-nfs-pvc
  namespace: media
spec:
  storageClassName: "manual"
  volumeName: media-shared-nfs-csi-pv  # kustomize namePrefix adds 'media-', matching PV: shared-nfs-csi-pv → media-shared-nfs-csi-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 110Ti
