---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: new-new-boplats
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/josmase/boplats-map
  ref:
    branch: main
