apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      containers:
        - name: node-red
          image: artifactory.local.hejsan.xyz/docker/nodered/node-red:4.1.7-20@sha256:cf2d5657f12faebffaf1cea10203f277a2445434dec6a997212080ec0080f6c5
          ports:
            - containerPort: 1880
              name: http
          envFrom:
            - configMapRef:
                name: default-app-config
          volumeMounts:
            - name: node-red-data-pvc
              mountPath: /data
          resources:
            limits:
              memory: 500Mi
              cpu: "1"
            requests:
              memory: 320Mi
              cpu: "0.1"
      volumes:
        - name: node-red-data-pvc
          persistentVolumeClaim:
            claimName: node-red-data-pvc-node-red-0
