apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      containers:
        - name: node-red
          image: artifactory.local.hejsan.xyz/docker/nodered/node-red:4.1.8-20@sha256:a5cb1dcdf90a7148b02b9dba4acfe6bd98c7bf3bff1e845dcdecfd7af3a95a29
          ports:
            - containerPort: 1880
              name: http
          envFrom:
            - configMapRef:
                name: default-app-config
          volumeMounts:
            - name: node-red-data-pvc
              mountPath: /data
          resources:
            limits:
              memory: 500Mi
              cpu: "1"
            requests:
              memory: 320Mi
              cpu: "0.1"
      volumes:
        - name: node-red-data-pvc
          persistentVolumeClaim:
            claimName: node-red-data-pvc-node-red-0
