apiVersion: v1
kind: Secret
metadata:
    name: gitlab-backup-object-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:W9F5n2VMi76V3TLTJ1zNU0y+VPatx2Fc1r11M5Lsi7lmCorbVDXDI3/we7+FEISm3eHrJ5fglmwDa8naN2BE8kwBCoMp3R0k5lFLFOCDky9G9DJHsIaqtI/XvbLoXe9NocdzcoA4ci1fXEqjlFGA3MFXDRLXJyLSzT7PBzDMYah9HjSum9RO1JO711uMAEukWt0TcFMWOEEXkuMIVfgKWbR/TTtaiyXCch8/8qJTLw8Riwp5XXRIepkYOcrRCa307jCtmDOv5M5PcQwwd5FAQC9GjVcSzxtMQowIwWH5r18JW39aZOv1tl+qxS14uKSI52LEniTq1iAatYsogRqa,iv:Bp0N1siLIxUXW9rCwb+0nUxmnwITPUxkIoyXY26jzZE=,tag:6wUUYnXxOV5ySUZepeWvsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bGcvSWhFS1I4SlZnWElG
            ampYSUJ3OTBseEprRHlIbW1ib3FSNkM2LzBBCmJuSzFPMGF3M1VadnZQSGQySGJr
            OGZVYWM3Y0dBUXlzWERId3RaOWtZWUEKLS0tIEJZZ1ZHV3B1L3NVZ2lKaWVBekxr
            MGUxUUpLV0tWOHlkT3UzMDFtMTlEMlUK1N9y1Az+dMFr2jT8vG1IhxlOD87cHz3v
            gYRgSEa6o4cIaWB+zgifTiN3akBLbvVjdV05U4/dPp832ChfL731fQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T07:47:49Z"
    mac: ENC[AES256_GCM,data:/zkUxGT8LiuX1A3n6a62JEDjWH9CydD2T+DBnlLBT58y1huQRFC5L0HVdLJQjIxPU0PANkS6GZDNpY73mU8q9qGoJ9cndY/hqg7i2W3KwBebSKtElVEVyrTFOmxlNbDMRX+HWPf5heYGb/DofkSMVnnQSdwYDoyPJkRQxHpMyjc=,iv:fERUpyfvq9mGrodyCmHIXy+XlXjM8AqEe/raeaU6ly8=,tag:gCuGtjIMXyOA5z68EYKkMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
