apiVersion: v1
kind: Secret
metadata:
    name: gitlab-initial-root-password
    namespace: gitlab
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Q0Bad5KtoRNQ46rX1UMRPY/ewHSqEXuLztqRK1HuZhX3gjrkeq4PF82dTML8nKvKBjs7L5A9v9yNnooULofJ/A==,iv:I9CmMZS/xF2xj7HY43NzE/rxzSlsMJ4Z7VcKZb+7YgM=,tag:DJaLZFfXvGNs5uxXzb4SQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZHpmQWh5eS9VMC9teElz
            RmdvUnd4clBFZzBFY0RLaldkMjZDYnh6eVc0Ck1mY0wxSTB0ODNPVkJHRkp5L0xn
            V25uTHh6cFhsQTdRT3ZKTHZPVG1EMW8KLS0tIDhWcWp3enJBSStodFE3N1JSbkVq
            RXZ5T2lNV1U3Uy8wVkdQcnlKOWtNSDgKpOCkAUHg6N2kY93ALbtazNZ+ZR3/6Fbj
            4hdIBFLtjk567r3BGT7kNhNtr1csdBezPDHOVggZ0/B5z0/lsbKjhw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T19:56:31Z"
    mac: ENC[AES256_GCM,data:jlNE+G7vSqnYcMu3wI1ewkgYCUE3gRvmXKrvhlNIHv/8yaP5sOaCkDv3zNbko1wjqD0VruZBfj/s0b9lvPHsyrs9/gGnrSwQsKL9Sz6S/VeJ4qYLRq/kvyVK3WBc2tMRCZhuvo5Sq9bibpS6Ig3dI97ZCpka46Sj3Rq1LAfQvh0=,iv:HlQwUAFpgP3SOKg6uqpgHNOQKBL7LbrpK0zpgGKcOEE=,tag:CsbRZi/jNTVbhEi98bjPWg==,type:str]
    version: 3.13.1
