apiVersion: v1
kind: Secret
metadata:
    name: gitlab-object-storage
    namespace: gitlab
type: Opaque
stringData:
    connection: ENC[AES256_GCM,data:BrY5voGz4LIkU2FJVIK8lcq4IF4NVaEUN3sAp3Z2XBL5wg++Dzv7kzHdnr4zPvaMIinH8i9Z2ZPcBXVrZC3fbrAlA/zk+Vu7Oinmur03O6UPWKiXhBFAg+EP6CLfWQodbQ9qiVr+mhH+w0vNl0W6Jt+Qtq6ZScan/8ZVqCGT3Jr4nppfcq6YKBcLahuqv+OTblJuj/jGcDsn/bBGINRHl7jjARuBvx7NN5Dc1ZXymjxHL4eGP8gtCxnUhI/qc3WoBoPo12/Iai0iM66Q49OnV0a0I/HJTlRO37SAA92u93mQIQ95zNz/HQ==,iv:DEFFfUZEwaKyD+IdGLVZ9x4KUYCECYUuP020bRvOb2o=,tag:cdgVU8a02A3EaBOPe6L+yA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTmc4bU9tZGQ1OVZZR0FH
            aCtHOFJwTS9NVjZ1ZW5wT053QW1JNmJsaW44CnFjbEpTSkR6NlBFOHJUZkdzWnh3
            VGxZaTQ5S3VwRU1KL1ZQZ1oxTlR1WjQKLS0tIGh1bHUrK0NsWml3K2t3M3NJckNE
            bWdtVG5Za2Npb29xOEJtSlFHZTc2K3MKnV9C8wNcxf7tbC3RW++C+3h7JrwP4FJD
            MFcFWTSHcD+1TT9K/pzRsf/pNUonNhm4hvmkiG0Ch7/YCJ3F4T6ciQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T07:47:49Z"
    mac: ENC[AES256_GCM,data:LT0y4kSSUGTRCB88UbhsftsoOygq7YCwOKAIIRwlMzfsg+6pBqGKLfLWoLmgI2X0PqLZNO9HsRNZeRcNNch75OMqO5NhctwMeqjBtflPQXvd7gdh/HOLEkft+ynNFGDoGEmv9PE/NsTzsfSY1fffYgo/CV/Rlnt1aXuEZJ65pB0=,iv:D96O0gp+fKDlsrMemNiTpjmAmiOh51uW2+B0jktDwAA=,tag:h38b+8wWL8qWocLZ0ZzXOg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
