apiVersion: v1
kind: Secret
metadata:
    name: gitlab-postgres-password
    namespace: gitlab
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:WMpBN2M2xG29xI2kt3FSieZ8yzJCKDHDsSfZmQ6qouzF73oObSa6CWdHyfeXGBjixx3QQ9HDvSIwxHUIlmcQYw==,iv:kiKvkvwYP+UykUEpxlx2TdS7vG57Y3NJ3+1CFPMoEEc=,tag:jJqEX0svDVRPvDNVmM6s9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbzVVa3dXckJMVzNtTlht
            SVAzdlBjUjlUUys1K3NKeWtPVTJMTmlWa1NJCndKR3JGdERja3dDdHBqVjRRUFZP
            bXNFeU1YRUFuR0ZJM0ZTQ3lEbVFNTG8KLS0tIFJENjZXTjNxREt2aWs4WFNnTUkr
            ZjVKbFVNcmo5V2RLSVFuV2plUGNreGcKqIfmjrVM1c8LiM16wcriOfNPVvivaRsz
            K/489wE0AguMChP2MC2esjnMR3VNOgpEnySzD6VD8vlOoJFQ/QJxFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T19:56:29Z"
    mac: ENC[AES256_GCM,data:R6ROZA3h4Ssfh32WmpMC6pted4HwIVYIiUTkw39Sjeqn1JS1hREu/dHMzPe0SyraQ7AxQfSBub/keHeXKO3JVMW7ZBe3IlDYlJUsFd1GUC8Gvb0vNK6PMrb9SKbt/uQpqYt0WBuFQGKrzsv6vEssCnfGbWGrMbLGc4B8IOi+6cM=,iv:YNzn6suQoXWboA6ACXZZBnF7A7O0eRrCvPbMAtzpMM0=,tag:+b5l5+vA6DF2uH3kXz6nFQ==,type:str]
    version: 3.13.1
