apiVersion: v1
kind: Secret
metadata:
    name: gitlab-redis-password
    namespace: gitlab
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:tucpUbZbz+7kqBg3jKE4wO/gSKzc1W9ft3jiaKVBcd5z7QUuzU2KfpdbVa2Yme5AopcssCu3iPsyM4NISeKF2A==,iv:uNSEr1z7s0vFZTathhHrgR4yp8ZGHEqX+9hfpwjzYv8=,tag:k18jQ9TRcvLC0gw0rRvaLg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeFh4V2d5dnFnZXhLN3Vm
            NHpyeE44QnpmQ29oME5hZURSMjNIbFhyR0FjClZpckVrNGFJQWd4cmhWTDJQbWVx
            TmlpbXhIWm1tWUhGRkQ3NmRVeVJPKzQKLS0tIEtDOHZhT0VBS1BTR2FrL0FxNEtp
            bmRoU0xEaWJhUTZQcDVwUHdxQ1RXWkEKRojhg6mUvCOKJSzrAJwd4chh3hWhT3lc
            XXFctnlOzHKXdXBERQLeSOyxOXx/2A0UBICo3TjyxbsS+3cmKEfwsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T19:56:30Z"
    mac: ENC[AES256_GCM,data:Xiu3GgFg8thJE6P9FK41lY+JbkyEc+S8dq7WrNkvLar7ZpzgL7DvrWnekvB3YQvBEP7ScpkkO4b3FKsYWVV25P6yUg8wSegWDO+LhpxghvB2566RFwe+pVa9rFNqMzl9A1Bgjo2hzW0BwUF+fAMo1IM5c5XJVeeIJE/9HdkrYAg=,iv:4ocz/71XglA8kMedz5TK3kdCbZvUlF3bEcOabvVnA+E=,tag:51cownIyHGc7p0132XACvQ==,type:str]
    version: 3.13.1
