apiVersion: v1
kind: Secret
metadata:
    name: gitlab-registry-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:1bvwkxjuYbPRU8TnazPh0F6Hb4Zl5tN6Ir45TWy/vR9dc7j5JSPvEL0QnrJ918SgN76HVGBzU/XJBNW7CGrEeTfrcojELvKAlQjAHkpXiIsITc006F7/QQ/rkZm8qlXBYw2Ixail8IZNP7InEApS2OnJc6q0Hk6MTI0EgoCQlQQDn1GTwCPPmNq1HThvo5jLXcgu9C1vOUP5fwSy7oOJkBLLKJwwdrrUPAPpx2+w9+Z5m8G63Arocy9Hmc6iLKXQFdPordAA/mtAE7jUvlHEp9yqNaxoJ1fzAw9K/Z/aA9UMMSrcukqWID5PDMqCH0rkiNZ7cxd3Fl8GKvIlPHQH5R0UprxrSI93dZ3xgz9Jrdsn21SCywSsWtiCESCJfq/f/PzVZvw2GnmDaMh1WgSpr+GDbrhx,iv:TwwCLXpLjm4bMR0cftg62EVLmvciYsYM7a/q1sk2jMg=,tag:nKJK9NArbpuA0WQxBeTIZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWFMvb2FmS2dnMFhBLytv
            cXA3REk4bW50WE1adEpjT0JUKzFlQndIaEYwCm1USUZYVU05Q1IrNTRoM0dBdHF3
            S1VtMktCVjU1Vk9kckFtS0Y0RVNpVEEKLS0tIG9pMkJHbGllY2VMYXRZejJ5L1d6
            WjdqN2lvWVc1bzJ6Wk5zRVpHZ0VHM28K6JnssScZ1SPAlMCKzBV6mwxNm0enSZ6R
            KbmHmLx19eNydt0Xw+cYW7tHnD3K7i1EhpZdJKp77EdMRuOcQ54+TA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T17:47:25Z"
    mac: ENC[AES256_GCM,data:WAMJCHX/lz3PGJ2zWkhIcWJJAN64h8auHGfmFcu01jvbgKEngNd+y+yFFE0BvKRuzvCKYy0oOKbfUZk3jCN3BWJ6hodVYDPh6C3AU0awSiER6/Bs5/wX/5ThXXF7HFAG8DidkYKI4XtlzX7cQ6ydhfIZYO2wzjDF4bEdt5FoNMA=,iv:3RusLfyO7G642OGKTgQLlChdCOPYESbp3i68l33DTGg=,tag:YMP2b2k9oi/Naq+xrEfXqw==,type:str]
    version: 3.13.3
