apiVersion: v1
kind: Secret
metadata:
    name: gitlab-registry-database-password
    namespace: gitlab
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:sqMRUn9qBfieMlS4imWH7MQ3WFJs2FCot3KXxbo+L7U=,iv:EXtj7EEfCH7GEsl1XAeZJTEtTajqaw3YTXM+3HeBumY=,tag:81BQX5m8uYx73W6K3I+Vmg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcDgvMjZnb0hueDZiVFhS
            cGNlSVIvUjFmcWtYSVYySUw1dG1UQ2ZDWjJRCnFUbExjM0hSM3JNcFVZNklvYUlF
            aUFNa2RMRHFCaU0xRHE2aENRbEdmYUkKLS0tIHUyWUtMK2dxOEhVWFZoa2FRWnVS
            OTR6TlUveFp0VnhmLzBFVTlta1U2SDAKTM6y//BuHIHoDxTPnXwymDMFtFKBvsg+
            yfaryipS1OmcJ0nL9FBV2f9VlZfDe60TQhtHsqTwN6aYCFYQoVRqTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T11:16:11Z"
    mac: ENC[AES256_GCM,data:rY53IuoKa71BtCYM44RAcLbfSHClJgyVEFUDrdtUqhjmcPG0/d+pTN7xOCFJIL85g+9fZfkc3NHLsjoBZKGINWU/PClH0Wi3XEDb/GvU7zBvVIq2fo1Rs9rFl1mAk8i0wb8MUO0dRlkN5j+Lh5j6/+98n/L+xBl03SA473IJ+Kc=,iv:dTT6HHel1nPTA1TAGWldtITKZEbVAdm0mUMUffbWy1A=,tag:ykbQK1NwWCVaGAfNH6GvEw==,type:str]
    version: 3.13.1
