apiVersion: v1
kind: Secret
metadata:
    name: gitlab-registry-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:fY2xXvIfmsbtIt6/595npqyDV8BT42ud5Hq5fjZ8En4m8hWIZ5VLTnJuhUBzuAXCG/7hw+rA2+1EZxnibYVaiZ94PkayG+zba5GJDCad59Yjpf1Hy7JMddB0HIGp+D4XD5xlJQMTdjOkdu79AaDPyeQxOdDVBxO0SGKeUiYhxv22kxK/odqljrTAsIB8d+1y1Hs3ZUkmW5j6XpDXjNfRDwy0op0WoZEWRLP6QwJj2zzLHT2Q95+HL467Z4b3Cp/OHwK77L5u+/atcHshZmLoTQdb/YseX+k8vhjHUGeuEuWsnpODmTdLHNKDlkKOfIy8PmodeXUdQYBv0hSLIpwUdzf1jBLWN9oi68k1eIOG83FglFkQLvUZilUA/SRQgB2c2vvOdlZdjd/akSmlJxPOi0eNOnYlUdzuRxwyoR2l+tVNN/4STZHs0nR/oLw=,iv:sRdQgnNSuRoo08ItgrjN0dzet7VXwY5opN/xCYm0LhQ=,tag:rD7XmjL9NYX2n2KkKOrDuA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTTdlTnJERFQwYlBja2V5
            bWJjQUNmczhYRTlQNXJhQnpsa09YV0EzdEZ3CndvRkxDVXg0aUVMNmo2MnFIWUpw
            aDFaMDNqR0lxZy93T0cvVDFNcnRxQ28KLS0tIFFPcnN5b0VVRHNBeTZvbDRuSThW
            cnlyejBFa2dtWnAxbENmOTk3b0RLdWsKNSpVvNirBGfyCXZUTo3BtsOmkdXs0KVL
            Ddh6WrScsfp4L8WxGCTSaBnBqXisLkra/lQBe/NFnJ1Pvl4iw58X+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T17:51:05Z"
    mac: ENC[AES256_GCM,data:661GalSScC2RuPJp68cpJuPGiz/OZ3VYnFfWqZT2PfOZzSvr/sCQsTO6oRsEV2pPF+HSN2sjLBKt2xyCe8QfFiayvD5Tz2ox8tnUZnxFnjT3N2s03cc1Mu1EOW5rcyjBcIC2zWuzSSOlIWEHpzih5//eOTIQHOwt1vjVznwXGhY=,iv:aQMXSX0zyyaywd83KWzpiNjzHIxf3ii5c0kk49Fk/aA=,tag:NHDn50Dln/5M4qpkv0ohaQ==,type:str]
    version: 3.13.3
