apiVersion: v1
kind: Secret
metadata:
    name: gitlab-registry-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:BnNJr8kbyeppx5rWzcAiafvGJTZVOGjMcWGUy+3DQWlovIJx8M79U28xvXAGBtA0l9yNAWFDRx6zvutJXJq4fJvg6c3gqMAwwbD8kDyzJNOUFLQvSCGICVaMMlBjr2xKheW73ECWFeQc/ef4OhAGE9YRmYYnvqcrMowsO+SWVudR687QOO5+cfgWFSvY/RW30bKfiAHjXTw6Hi6PPw7g7mzsUxiDKR25PyDYm4AbupzwNMrbZ3HxX/cGTQXKi+U7AArAzXoUJTlFgB8goZzTRpl8WXaYtak6g0Gh5xY8ZQgfUhVvgwA3+7ySFHeOg8NWeBK++MvlGT14ts0kxei45jqTM/n4vL6HorSpkOrGI7KpCg==,iv:LV4SFRreFp8k2/2G/tjdPSRLIk98vDT8fOiTIZ9/Ac8=,tag:YLtUxZ7bvfonrlC/bQX03Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK1pybmdrOERzcHExaThL
            am1KQnplMHVuWDlQeS9iRTRvL20xRGt0UkFVClR6VDRpdy9sTXUwdXJsUmVZdUdC
            OHVrNUxXUTFieXN3eC9IbVdDN3lyRk0KLS0tIE0vc24zVzJ0ektheWE5dmQ1aWJH
            VkNwSGErZkcvd0hUK28yQlNRQnBuVFUK6H5A1xML7KfnhZr0+QlrllWMXh6l3V1E
            BMzysCIUhzFnlxGLZflDVS/BQqhGh9YPKyV5WKGl+o8ScruSpOz5CQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T17:39:14Z"
    mac: ENC[AES256_GCM,data:S6M/UUQCIWiFBSs0r8pNT7JkAeXW1kHaTnh4ulr7d2gVkjdbG+az1CBfiHYkv1EzHnTN0vlxOP/9QxpvwnueG8awstUj2/HWKc2Lvi14zgsww3lrTgRnZeYhHAXYSr8WdSrdaLff04WR+p6dE9pOx2d79L8KuC15Lp5XKBagpn4=,iv:FpCDzPQza6sSvVhlqKqQoCGhAPdabSpJ0uxX8ODFJD8=,tag:pVaoMIDTHp+EaX/62XFPwg==,type:str]
    version: 3.13.3
