apiVersion: apps/v1
kind: Deployment
metadata:
  name: pterodactyl-panel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pterodactyl-panel
  template:
    metadata:
      labels:
        app: pterodactyl-panel
    spec:
      containers:
        - name: panel
          image: ghcr.io/pterodactyl/panel:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          env:
            - name: APP_URL
              value: "https://pterodactyl.${DOMAIN_INTERNAL}"
            - name: APP_ENV
              value: "production"
            - name: CACHE_DRIVER
              value: "redis"
            - name: SESSION_DRIVER
              value: "redis"
            - name: QUEUE_CONNECTION
              value: "redis"
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_HOST
              value: "pterodactyl-mysql"
            - name: DB_PORT
              value: "3306"
            - name: REDIS_HOST
              value: "pterodactyl-redis"
            - name: REDIS_PORT
              value: "6379"
            - name: APP_KEY
              value: "4617739db9424a37ddf33ff499e234dd"
          envFrom:
            - configMapRef:
                name: default-app-config
            - secretRef:
                name: pterodactyl-secrets
          volumeMounts:
            - name: panel-storage
              mountPath: /var/www/html
      volumes:
        - name: panel-storage
          persistentVolumeClaim:
            claimName: pterodactyl-panel-pvc
