---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: downloader
spec:
  replicas: 3
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: downloader
  template:
    spec:
      containers:
        - name: downloader
          image: artifactory.local.hejsan.xyz/docker/josmase/downloader:v0.0.63@sha256:0382d12e134e904b5fed4645bec708fd2181e13f16abc045d1a376308d447e3f
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"

