apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-data-resized
  namespace: artifactory
  labels:
    app.kubernetes.io/name: artifactory
    storage-migration: artifactory-2026-09
  annotations:
    storage-migration.source-pvc: artifactory-volume-artifactory-0
    storage-migration.target: 50Gi
    storage-migration.phase: prepare
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
