apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: immich-machine-learning
  template:
    metadata:
      labels:
        app: immich-machine-learning
    spec:
      containers:
        - name: immich-machine-learning
          image: ghcr.io/immich-app/immich-machine-learning:v1.140.0
          envFrom:
            - secretRef:
                name: immich-secrets
          volumeMounts:
            - name: immich-model-cache-0
              mountPath: /cache/0
            - name: immich-model-cache-1
              mountPath: /cache/1
            - name: immich-model-cache-2
              mountPath: /cache/2
            - name: immich-model-cache-resized
              mountPath: /cache/resized
          ports:
            - containerPort: 3003
          resources:
            limits:
              memory: 1Gi
              cpu: "0.5"
            requests:
              memory: 512Mi
              cpu: 50m
      volumes:
        - name: immich-model-cache-0
          persistentVolumeClaim:
            claimName: immich-model-cache-ml-0-linstor
        - name: immich-model-cache-1
          persistentVolumeClaim:
            claimName: immich-model-cache-ml-1-linstor
        - name: immich-model-cache-2
          persistentVolumeClaim:
            claimName: immich-model-cache-ml-2-linstor
        - name: immich-model-cache-resized
          persistentVolumeClaim:
            claimName: immich-model-cache-ml-linstor
