apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-model-cache-final
  annotations:
    storage-migration.source-pvc: immich-model-cache-immich-machine-learning-0
    storage-migration.phase: cutover-complete
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor-final
  resources:
    requests:
      storage: 1Gi
