apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-model-cache-resized
  annotations:
    storage-migration.source-pvc: immich-model-cache-immich-machine-learning-0
    storage-migration.phase: prepare
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: ${STORAGE_CLASS}
  resources:
    requests:
      storage: 1Gi
