apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secrets
type: Opaque
stringData:
    SONARR_1_API_KEY: ENC[AES256_GCM,data:eeEdtX/SAKKRgFXib7eldUBxTWcfQvjcZYc7,iv:++BFxtNvzNnCTSjuzh9kF+tmKRHhZLegVW241tU3w4A=,tag:fCQMnAR5RRN2iNY/3JJ6XQ==,type:str]
    SONARR_2_API_KEY: ENC[AES256_GCM,data:RxSuXGKfqW6RAi24lIhvewJDh2Wu3JzU681W,iv:SN8gtXyhQeEwxwNg55hz9NMcEJgxTVjk0pQqSuKxXyk=,tag:4q7QuA/a6LnfAghypO62lA==,type:str]
    RADARR_1_API_KEY: ENC[AES256_GCM,data:X8w5/jka7lwZVhFSVPmcMHLcL+QDogj2Yc2M,iv:CuQDvk64pb0FSy+RlE64Ycr3bORNUkAavA0rXpKUA6s=,tag:BbePrqmb9wlNL+KwXxlaUA==,type:str]
    RADARR_2_API_KEY: ENC[AES256_GCM,data:wa6MiyZ0jy7EOp02ltsurAnsNPQYbj2DnKG5,iv:MoWrqgrkeSxds4G9ejPgtO9EqZvVuHWLnc/kOBjZdGk=,tag:66pnETVO6GKEv7U3w9uwXg==,type:str]
sops:
    age:
        - recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0blBYNk50ZkNLVnR4MlM3
            QVU2WWlaU2o5TnFLK3liWHZHYnIzc0tKNUJBCkI3SU1zTjVzUWVWcFVZTEowOUJO
            Sk9TZjFBY2xjM1dEQW1EQnp6aGFUWXMKLS0tIGpuWHhvSDQwTzVZRTdxeVh4VFY0
            NzFQb3Q4SXdRekFvUXdvVDRScGNBdVkK9PgAYPuZXZxWvJ9a1pdz98VM+0IC1zWU
            7TKhqUQnXaRvq2u9RGvsrpoNiwMtqmtSKd3NlQhNFdG1NMQQVL+unw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T19:20:18Z"
    mac: ENC[AES256_GCM,data:CKI9UzYQtKIQe4ZXZ+OqZHpEkJhYxWwLUKr3BD3qujf0AXLZNv+imyFw89Hh+s+IXaRFI5IKrXc3UpHp4ddFchhIYTJMcYcxiG4QRoL2Of0WjMdqilnUIwWiu9h9qNPNgBpRUc5jTFtD2STw68IrJNKl8pnoGFtve7GFCstftmc=,iv:uoQjARWMAyGJ4FX0G96Qmvq4KQQ4H+sXPzVBynI/DCY=,tag:rVWIzozJs6GPHy13KMVlBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
