apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zero-cache-data-linstor
  labels:
    app: zero-cache
    storage-migration: zero-cache-linstor-final-2026-09
    storage-migration-phase: final-active
  annotations:
    storage-migration.source-pvc: zero-cache-data-resized
    storage-migration.target: 1Gi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linstor-final
  resources:
    requests:
      storage: 1Gi
