apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zero-cache-data-triple
  labels:
    app: zero-cache
    storage-migration: single-class-pilot-2026-09-22
    storage-migration-phase: final-active
  annotations:
    storage-migration.source-pvc: zero-cache-data-resized
    storage-migration.target: 1Gi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linstor-final-triple
  resources:
    requests:
      storage: 1Gi
