---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zero-cache-data
  labels:
    app: zero-cache
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
