apiVersion: v1
kind: Secret
metadata:
    name: odysseus-secrets
type: Opaque
stringData:
    ODYSSEUS_ADMIN_PASSWORD: ENC[AES256_GCM,data:LWypZ6so1IcCTYvQsd8Eaw6qOubVbFMpQk//kXJVmFA=,iv:10ZYiTdNSXliMWzRb6f/H8kDwslAGk9MxYoyxjDmR+k=,tag:v7SMdqHEKOE16Yox+eEKBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcGxrM2d1Qk15RXY4QjB0
            V1l1M1pRUFZOWmNQS2hoWGZ2alJCYmx6dzN3Cm9sbnh0b01LQ0REcklLYzFKRVBs
            RFYzVTVReTA2SUordHFubWp4Q0JCT28KLS0tIEtxb3Q5eHhvV0t5RjVNV3NlN3Ra
            OTZBTUVCbFcwMmYxaXNTdm94bG4yeEUKuKo1ahHM5tsSPwGdT7eSSc7YwofRY+vD
            w5U98jU7/xu+408VG8tq6GObgsrELBXR75ZjxNAHGRvUk5wJyEctrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T20:53:02Z"
    mac: ENC[AES256_GCM,data:JdgGzA+dNl/PDUWcn1h3TTK3YnHA8qNNLGJgwjAddwWGQaFYHTveqBATnJewzdT57we3jfBIckbRwrMZS+mDK0PETTjoHB22phFXRga7JYiu7woihIueRHDoi5AMvd/8wR4VB6sm7Rz8XZh8ulG3A2FAC9kMu7OQu6ddjAwTCiA=,iv:TUpTykAnTK7a+cFSIRl8cEGpBM/E+5XtrSXA5INsw9c=,tag:kNs0iFCqJO+62W3O20trIQ==,type:str]
    version: 3.13.1
