apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-linstor
  labels:
    app: radarr-6
    storage-migration: radarr-6-linstor-final-2026-09
    storage-migration-phase: final-active
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor
  resources:
    requests:
      storage: 2Gi
