apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: data-to-canonical-v2
  namespace: media
spec:
  volumeSnapshotClassName: linstor-snapshot
  source:
    persistentVolumeClaimName: radarr-6-config-triple
