apiVersion: v1
kind: Secret
metadata:
    name: pterodactyl-secrets
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:qqjsCfoVuxLbuEg=,iv:cmKB3WKGD3JraX39u+GYMvPI+vFfwyRlCQITui3rClE=,tag:LiUtuYHOc7qTFf+yKVQ3nw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:iFVCwICK5SGzn/byEkZxcLKN,iv:iNBPb7gZc2vUYN+CRsxPhZgkNGfWFRmyfl7JxaD0ZgY=,tag:X6q8jY/4zK/2F5j++qX1jw==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:AXD6lJylD8y7pug=,iv:oSBc/pNe+AO3oVi4pljFll13rd46TS+0f0nn+yZ6NOE=,tag:hnXAdC/uHNBsbgBT2jya1w==,type:str]
    APP_KEY: ENC[AES256_GCM,data:vLZ9EbxiyE5S5VIsSIXFwlLeUkA8PsdGHSTdjhShWZA=,iv:n4f0j2XkDMpuMU802hgl7A+kQVVO9UEU4uNVtnETvvw=,tag:jwqPONw8Xe60LVGQVNorTQ==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:o3dOHL1SVEBDXhaGP3+fffozl0t9W3U=,iv:phOXoS4DRBJvfA5O88a3sze72OP9F0uPLTRSwa6fgPA=,tag:9aVl52fiENtWpemhQjy0GA==,type:str]
    CACHE_DRIVER: ENC[AES256_GCM,data:Ez2IWms=,iv:Y3UfSCL6ElVVZmQFDcFXc4JnI98eXItQVrdMbu5fFw8=,tag:YuFowIlnuDOaH1Z6+m/u/w==,type:str]
    SESSION_DRIVER: ENC[AES256_GCM,data:/UM2xmM=,iv:aZUNONHTy/rVnjanpSET3pno9GKZNXSid2qB+HdQYHY=,tag:PEUirHSbu35RNZAAM2ceig==,type:str]
    QUEUE_CONNECTION: ENC[AES256_GCM,data:ku0T7ak=,iv:iEt73Us4YYf2I+9mBfLt7x8UahbLPYjPg7HdtxTSc7A=,tag:be7bEHFRIOgm+6VHwRrcwQ==,type:str]
sops:
    age:
        - recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVYm9yVzNVUmQvQzNTblNZ
            Z2VoSEZRUGg4TG9iaytpK2svWEQ1NjVNbXlVCmdnVU1hTXg3MFl1b3RHMjdYTzVN
            ZXBSbGFYNS82RC9vZG13V3JsODFpN0EKLS0tIHRnZDdFaDdkb21GMEFhdTVxV3ZV
            MnVEWGl6N3ZzcGw5NlNGMDJjK21sODgKjxKOPQfuFXzLkj2vEFTiw3uYesnIErhC
            +eOW5Iv9pEo5QHMW0xmsS2ja5zWTDMgu2RJneVJlVm5+k5D6QkMAbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T15:44:39Z"
    mac: ENC[AES256_GCM,data:cwpyu2xLsa4RdPApR0+yzwK9zmXb7NumdwBpKvsKMAqaHQAttY4gED1BSMJbzZnbVb/LxI13Zl5VXo9TDepMb0xbDDqziQpS29iWgsIDxeHIUa8I1RLUNRZHlq0WS0WPSksdXcoywitGmas8DHOIIzLf5/jSRPIMqgbFpBdUvck=,iv:+J+kz1FqlA5BdzSoTjSXThie4XkVxXicceCtxHP4gEs=,tag:ZiXvHaau2REE1ubOPBqc+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
