apiVersion: v1
kind: Secret
metadata:
    name: pterodactyl-secrets
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:B7XnabLZ/2tvLMw=,iv:Opcf3iI7Va7M+vAJU2h88WlAv/otZCQiQdLKe4yQ8tQ=,tag:L/Wtqzw9gGJbGO7nSPvp8A==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:zu3DdL15RiJtJvxB4II3eGKV,iv:zzZLr5zNzOeuFNXQyf9hj0l0riqk1B2PMxFOaLnDaSE=,tag:iN6lvKopbfpPgMULiOTHhw==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:UgV3CYoO3812iec=,iv:TeK2IlgLazSLvwDaQbvs4VNcsVWge6YV87uIaT49DEo=,tag:z9alfHp3kEaORZ2EqsJ2bA==,type:str]
    APP_KEY: ENC[AES256_GCM,data:aQ9SvjQQxmvtmqfMR5njj5k15/r5jHuXCN1g,iv:oaz8OGG7J4jbal9vdQque6TXsI8t03xHVKJmou0Dk3o=,tag:uZ4kyp8Qc4udfurSEV+a5g==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:hXfJoCy1aHGXiw+Bo/pQvQIKc3ecf5o=,iv:a/HBpPDDgvCWZKyo/1BHqy9F/FWU53I3S+vUqrgnSv8=,tag:7wvTFbg5V3NMJ6HMEG7bow==,type:str]
    CACHE_DRIVER: ENC[AES256_GCM,data:Pe6v6nI=,iv:lZeg0ysHCnR1tXfkT+m6XgrC7ckVnWcyTkfbwgpprYU=,tag:73fB6LbiUP4G+KMUvW6g4w==,type:str]
    SESSION_DRIVER: ENC[AES256_GCM,data:dQJ8EEk=,iv:K7hgHjmDgVbzmOTZ1toL//ggPnSjGpRFZWvvqzwF5Ig=,tag:XGfYUckYt8HWH+L/TnELBw==,type:str]
    QUEUE_CONNECTION: ENC[AES256_GCM,data:e+tQWyU=,iv:XMGxnZnep/Ga30eBMpwiohDEUUSwSBidIxR4wBwz7U4=,tag:9EqkTCj0jrXes6eacjEE6A==,type:str]
sops:
    age:
        - recipient: age1crq59usy028utgwh2xfghs3hyykwn2hmgdvv4hxlhgasw0gre43q88y0kx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWjU3Y2ZRRVBUdnZwYnNx
            UmlVUEp1QUtCenZTTFpGZUtCcjNnY1ZldFNZCkRGNU0vQzVNMWM5WS84M1NDdXpQ
            WEw2d3o5eWZSRk5mQWZkdE9rZU9DUWMKLS0tIHJvU3Y2cDdISDJYT0kwTlFQOHhB
            Ky9LRlJDdGJmeGV0ZlNCWm1QMmVpaG8K4QU8lx3m37567J7fy4C0ZNsRaZW0HMyX
            OLKtjRLwJdq81HFTlwbb+GCcQu/Tj52HRvHA/shpJqYiMT6FIWyYfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T15:10:22Z"
    mac: ENC[AES256_GCM,data:A4yLBDUTe4K5DoOhjzqOklLyanko3hEpMqJJCX6ldgp3Ags8deZcK7D2hVzcSts/Ufi67o5hQADn2KwefacfIdLEilbPEXbKx0VV97gQqIKXeon3J4phy4uu+H3mkzBt9pOQhdwkcZRuvgnoAm73qUZF/E4/hDlVtPSBzG8aPF4=,iv:viwRyDPhnK8ul63Oil67V+lHE7rWr3ZCYEnTLraTOGg=,tag:TQP7E1ggCabynypIJYux/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
