apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-switchboard-data-linstor
  annotations:
    storage-migration.phase: canonical-blank
  labels:
    app: llm-switchboard
    storage-migration: llm-switchboard-linstor-final-2026-09
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linstor
  resources:
    requests:
      storage: 1Gi
