apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-linstor
  annotations:
    storage-migration.source-pvc: sonarr-3-config-resized
    storage-migration.phase: copy-target
  labels:
    app: sonarr-3
    storage-migration: sonarr-3-linstor-final-2026-09
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor-final
  resources:
    requests:
      storage: 1Gi
