apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - radarr-1
  - radarr-2
  - radarr-3
  - radarr-4
  - radarr-5
  - radarr-6
  - radarr-7
  - radarr-8
  - radarr-9
  - radarr-10
  - radarr-11
  - radarr-12
