apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-triple
  labels:
    app: radarr-7
    storage-migration: radarr-7-linstor-final-2026-09
    storage-migration-phase: final-active
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor-final-triple
  resources:
    requests:
      storage: 2Gi
