apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-resized
  labels:
    app: radarr-7
    storage-migration: radarr-7-config-2026-09
    storage-migration-phase: cutover-complete
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources: {requests: {storage: 2Gi}}
