apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkrr
spec:
  template:
    spec:
      volumes:
        - name: checkrr-config-pvc
          persistentVolumeClaim:
            claimName: checkrr-config-linstor-v5
