apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: minecraft
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
        - name: minecraft-server
          image: artifactory.local.hejsan.xyz/docker/itzg/minecraft-server:2026.9.2@sha256:de5d1b1a83eba576f6c8a688fac2a3523ce457724cdebc8ea48d7818b74cdf6e
          imagePullPolicy: IfNotPresent
          env:
            - name: EULA
              value: "TRUE"
            - name: MODE
              value: "survival"
            - name: TYPE
              value: "VANILLA"
            - name: VERSION
              value: "26.1.2"
            - name: INIT_MEMORY
              value: "3G"
            - name: MAX_MEMORY
              value: "6G"
            - name: USE_AIKAR_FLAGS
              value: "TRUE"
            - name: ONLINE_MODE
              value: "true"
            - name: ENABLE_RCON
              value: "TRUE"
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minecraft-secrets
                  key: RCON_PASSWORD
            - name: ALLOW_FLIGHT
              value: "TRUE"
          ports:
            - name: minecraft
              containerPort: 25565
            - name: minecraft-rcon
              containerPort: 25575
            - name: metrics
              containerPort: 19565
          resources:
            requests:
              cpu: 250m
              memory: "4Gi"
            limits:
              cpu: "1"
              memory: "6Gi"
          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 60
            periodSeconds: 10
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
            - name: minecraft-modpacks
              mountPath: /modpacks
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-data-triple
        - name: minecraft-modpacks
          persistentVolumeClaim:
            claimName: minecraft-modpacks-triple
