apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-data-pv
  labels:
    app: minecraft-server
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: pvc-1c52c07e-ccee-4fff-a58a-72558cd1722f
    volumeAttributes:
      numberOfReplicas: "3"
      staleReplicaTimeout: "20"
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  selector:
    matchLabels:
      app: minecraft-server
  resources:
    requests:
      storage: 20Gi