
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data-pvc
  namespace: minecraft
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-modpacks-pvc
  namespace: minecraft
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi