apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data-triple
  namespace: minecraft
  annotations:
    storage-migration.source-pvc: minecraft-data-pvc
    storage-migration.phase: cutover-complete
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor-final-triple
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-modpacks-triple
  namespace: minecraft
  annotations:
    storage-migration.source-pvc: minecraft-modpacks-pvc
    storage-migration.phase: cutover-complete
  labels:
    app: minecraft
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor-final-triple
  resources:
    requests:
      storage: 1Gi
