apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data-linstor
  namespace: minecraft
  annotations:
    storage-migration.source-pvc: minecraft-data-resized
    storage-migration.phase: copy-target
  labels:
    storage-migration: minecraft-linstor-final-2026-09
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor-final
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-modpacks-linstor
  namespace: minecraft
  annotations:
    storage-migration.source-pvc: minecraft-modpacks-resized
    storage-migration.phase: copy-target
  labels:
    storage-migration: minecraft-linstor-final-2026-09
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor-final
  resources:
    requests:
      storage: 1Gi
