apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-linstor
  labels:
    app: radarr-10
    storage-migration: radarr-10-linstor-pilot-2026-09
    storage-migration-phase: target-ready
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: linstor-pilot
  resources:
    requests:
      storage: 2Gi
