---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: new-new-boplats-api
spec:
  replicas: 3
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: new-new-boplats-api
  template:
    spec:
      initContainers:
        - name: drizzle-migrate
          image: artifactory.local.hejsan.xyz/gitlab-registry/josmase/apps/boplats-map/api:2026-06-10-8b523045
          env:
            - name: "DB_URI"
              valueFrom:
                secretKeyRef:
                  name: boplats-api-connection
                  key: uri
          command:
            - bun
            - x
            - drizzle-kit
            - migrate
            - --config=libs/database/drizzle.config.ts
      containers:
        - name: new-new-boplats-api
          image: artifactory.local.hejsan.xyz/gitlab-registry/josmase/apps/boplats-map/api:2026-06-10-8b523045
          env:
            - name: "DB_URI"
              valueFrom:
                secretKeyRef:
                  name: boplats-api-connection
                  key: uri
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
