apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

resources:
  - ../../../base/persistence/media
  - namespace.yaml
  - default-app-config.yaml

components:
  - ../../components/prune-protection
