apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/media/radarr-template
  - persistence-resized.yaml
  - persistence-linstor.yaml

namePrefix: radarr-12-

labels:
  - includeSelectors: true
    pairs:
      app: radarr-12

patches:
  - target: {kind: Deployment, name: radarr}
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
        value: config-final
  # Patch the IngressRoute hostname and service reference
  - target:
      kind: IngressRoute
      name: radarr
    patch: |
      - op: replace
        path: /spec/routes/0/match
        value: Host(`radarr-12.${DOMAIN_INTERNAL}`)
      - op: replace
        path: /spec/routes/0/services/0/name
        value: radarr-12-radarr
  - target: {kind: Deployment, name: radarr}
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/hostname: kubernetes-node-204
  - target: {kind: Deployment, name: radarr}
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/startupProbe
        value: {httpGet: {path: /ping, port: 7878}, periodSeconds: 10, timeoutSeconds: 5, failureThreshold: 30}
